- package.json
- yarn.lock
Fixes #14.
Adds deploy scripts using `yarn deploy`.
https://medium.freecodecamp.com/surge-vs-github-pages-deploying-a-create-react-app-project-c0ecbf317089#.wtuzwpp15
> Deploy to gh-pages

- .storybook/config.js
The logic for importing all files called 'story.js' was wrongfully matching against any filename ending with 'story.js' (eg. 'history.js')
Rewrote import logic to only match files with that filename in the /src/components directory
> Fix React Storybook

- src/index.js
This PR fixes the broken routing on GitHub pages.
Although the authoring prototype was being deployed correctly, routing was broken and lead to 404 error being displayed when the page loads.
This fix sets the `basename` for the router history so that the react router can successfully resolve the correct components to load based on the browser history path.
> Fix routing so that author deploys correctly to GitHub pages.

- package.json
- src/index.js
Updates the `package.json` to reflect the name change of the GitHub repository.
Also React routing broke with the name change so this PR also aims to resolve the 404 error currently seen when Travis CI deploys to the[ GitHub pages](https://onsdigital.github.io/eq-author/).
> Update node package name and basename to reflect repo name change.

- src/components/App/index.js
- src/components/Forms/Input/index.js
- src/components/Options/Answer.js
- src/containers/DesignSurvey.js
To add another option tab at the bottom to allow the user to change the q_code and state wether a survey is mandatory or not. 
- Start the author tool and load in a schema
- Go to an answer and click the "Mandatory Guidance" tab
- Inspect the browser page using the "redux" tool to look for the changes in state of the answer while editing the q_code field and checking/unchecking the checkbox 
- The state of the mandatory field should change from "true" to "false" depending on wether the checkbox is true or not
- The q_code should simply update the state with each character entered into the text field
> WIP Mandatory settings checkbox

- src/components/Forms/Input/index.js
- src/containers/DesignSurvey.js
Fixed style code that was missing due to the rebasing and squashing from the last commit #93. This caused the input fields to be at auto sizing rather than 100%. 
Also missed code to do with the if statement refactor in the "designsurvey.js" 
Check to see if the text fields are the normal size they should be
> fixes wrong style code pushed from last request

- src/components/Sidebar/SidebarSection.js
- src/components/Tabs/TabList.js
- src/components/Tabs/TabPanel.js
- src/components/Tabs/Tabs.js
- src/components/TreeMenu/AddIcon.js
Fixes issue with non-rendering tabs in production build.
- better usage of displayName property to check child component type
- fixed styling issue with sidebar
- run `yarn build`
- cd into `build` folder
- `python -m SimpleHTTPServer 8000` to spin up a server
- check tabs render as expected
> Fix Tab rendering in prod

- .codecov.yml
- .travis.yml
- package.json
This PR is all about enabling codecov.io to produce coverage reports for the eq-author application.
- Enabled eq-author repository on codecov.io
- Added Jest configuration to collect coverage report.
- Added extra step into travis configuration after_success.
Check that codecov.io analyses the eq-author project and that relevant and helpful errors are displayed if coverage fails checks.
Appropriate rules have been set to help enforce a high level of test coverage.
Agree any additional coverage checks other than Jest if necessary.
> Add codecov support for eq-author

- .codecov.yml
In an attempt to avoid failing PR branches while the test coverage is low, this PR has been raised to change the codecov configuration to set the target coverave for the project to `auto`.
This should help to ensure that project coverage must increase from parent commit or pull request base.
Codecov analysis should be a bit more forgiving during the early stages of the project.
> Change target coverage to auto.

- src/actions/survey.js
- src/actions/survey.test.js
- src/actions/surveyItems.js
- src/containers/CreateSurvey.js
- src/containers/DesignSurvey.js
- src/pages/CreateSurvey.js
- src/pages/CreateSurvey.test.js
- src/reducers/survey.js
- src/reducers/survey.test.js
- src/tests/utils/mountWithRouter.js
Fixes #101 
Changes elsewhere in the application surfaced a bug whereby the survey meta (title, etc) was no longer being stored in state.
I have moved the survey meta into it's own piece of state and wired things up accordingly via an action.
- Visit `/create`
- Enter value in fields on the "survey meta" tab and check that those changes are persisted in state via the Redux dev tools
> Wire survey meta up to state

- .travis.yml
- README.md
- package.json
We should only collect code coverage on CI server, to speed up local test runs.
1. Run `yarn test`
2. Observe no code coverage reported
3. Ensure code coverage reported on Travis build log
> set code coverage off by default

- package.json
- src/components/Breadcrumb/breadcrumb.test.js
- src/components/Breadcrumb/chevron.js
- src/components/Breadcrumb/chevron.svg
- src/components/Breadcrumb/index.js
- src/components/Breadcrumb/story.js
- src/components/ButtonGroup/__snapshots__/buttongroup.test.js.snap
- src/layouts/WithSideBar.js
- yarn.lock
Refactor the breadcrumb component so that it more closely matches the new design.
Mostly stylistic updates, functionally should behave the same as before when an array of links is passed to it.
The breadcrumb defaults to the Dark theme (as per the design). But you can switch it (see the story for an example of a Light theme).
I added some additional Jest tests to cover some of the breadcrumb functionality.
Since the breadcrumb sits within the Header, some additional tweaking may be required to get it looking as expected.
All tests should pass.
Existing behaviour should continue to work.
Style of breadcrumb should match the designs.
> Re-work of Breadcrumb component to match the new design.

- package.json
- src/components/ButtonGroup/buttongroup.test.js
- src/components/Nav/nav.test.js
- src/components/Title/title.test.js
Adds snapshot serialiser to the package.json config so that there is no need to call `toJson` manually on components when snapshot testing in Jest tests.
See the [trello card](https://trello.com/c/ruqTDweN/66-configure-default-snapshot-serialiser-in-packagejson) for more information.
All tests should continue to pass.
Functional tests should pass.
> Add snapshot serialiser to package.json config.

- .travis.yml
Adds the production build step back into Travis build so that compilation errors don't go unnoticed.
The travis build won't deploy this build anywhere right now, but at least this change should help us catch any build compilation errors.
Production build is performed as part of travis CI.
> Add production build step back into travis build.

- src/components/QuestionnaireDesign/CanvasSection.js
- src/components/QuestionnaireDesign/CanvasSection.story.js
- src/components/QuestionnaireDesign/CanvasSection.test.js
- src/components/QuestionnaireDesign/__snapshots__/CanvasSection.test.js.snap
Clicking on a CanvasSection should be the same as tabbing into a field - optional && empty inputs become visible. Currently this is not the case. This PR fixes that.
Run tests. Inspect code. Test in browser:
1. go to QuestionnairDesign page
2. delete text from *section description field*
3. tab to another section
4. observe *section description field* is not visible
5. click anywhere in Section section (uh, naming)
6. observe that *section description field* is now visible, even if no field has focus
> allow focus on CanvasSection with a click

- package.json
- yarn.lock
Fixes issue with react-apollo v1.4.3 which prevented you from testing modules that internally used react-apollo 
Run tests, ensure pass. There are already some tests in the suite that would fail under react-apollo 1.4.3, so all tests passing serves as proof of fix.
**EDIT:** this does not fix issue 160, not sure why i thought that
> upgrade react-apollo

- src/tests/utils/MockDataStore.js
- src/tests/utils/MockDataStore.test.js
- src/tests/utils/MockResolvers.js
This PR extends the Mock API and adds the ability to add/update/remove Options for a given Answer.
It also mimics the behaviour expected by the real API, by adding default options for Radio and Checkbox answers.
The Mock API yields the expected results when used by the application.
The Mock API has enough functionality concerning Options that development can continue on the Checkbox answer story.
> Adds Options to the Mock API

- src/containers/QuestionnaireDesignPage/index.js
- tests/.eslintrc
- tests/pages/DesignQuestionnaire.page.js
- tests/spec/smoketest-author-spec.js
This fixes #181 where the only page of a section could be deleted, but a new page would not get added.
delete only page in a section, observe that new page is added
> fix bug where only page in section could not be deleted. fix #181

- package.json
- src/components/IconButton/IconButton.test.js
- src/components/IconButton/__snapshots__/IconButton.test.js.snap
- src/components/IconButton/index.js
- src/components/QuestionnaireDesign/__snapshots__/QuestionnaireDesign.test.js.snap
- src/components/QuestionnaireDesign/index.js
- src/components/QuestionnaireNav/PageNav.js
- src/components/QuestionnaireNav/__snapshots__/PageNav.test.js.snap
- src/components/Tooltip/__snapshots__/tooltip.test.js.snap
- src/components/Tooltip/index.js
- src/components/Tooltip/story.js
- src/components/Tooltip/tooltip.test.js
- yarn.lock
This PR extends on work previously done in #185 to add the missing acceptance criteria (missing styled tooltip).
A new Tooltip component has been introduced which wraps any components which require a tooltip to be displayed.
Other areas of the application can re-use this to add tooltips which are consistent with the design.
A tooltip should be displayed when hovering over the Delete answer button.
> Add tooltip to delete answer

- .travis.yml
- src/components/AnswerEditor/__snapshots__/answereditor.test.js.snap
- src/components/AnswerEditor/answereditor.test.js
- src/components/Answers/BasicAnswer/BasicAnswer.test.js
- src/components/Answers/BasicAnswer/__snapshots__/BasicAnswer.test.js.snap
- src/components/Answers/BasicAnswer/index.js
- src/components/Answers/CurrencyAnswer/CurrencyAnswer.story.js
- src/components/Answers/CurrencyAnswer/CurrencyAnswer.test.js
- src/components/Answers/CurrencyAnswer/__snapshots__/CurrencyAnswer.test.js.snap
- src/components/Answers/CurrencyAnswer/index.js
- src/components/Answers/Dummy/TextArea/index.js
- src/components/Answers/Dummy/TextInput/index.js
- src/components/Answers/NumberAnswer/NumberAnswer.story.js
- src/components/Answers/NumberAnswer/NumberAnswer.test.js
- src/components/Answers/NumberAnswer/__snapshots__/NumberAnswer.test.js.snap
- src/components/Answers/NumberAnswer/index.js
- src/components/Answers/TextAnswer/TextAnswer.story.js
- src/components/Answers/TextAnswer/TextAnswer.test.js
- src/components/Answers/TextAnswer/__snapshots__/TextAnswer.test.js.snap
- src/components/Answers/TextAnswer/index.js
- src/components/Answers/TextAreaAnswer/TextAreaAnswer.story.js
- src/components/Answers/TextAreaAnswer/TextAreaAnswer.test.js
- src/components/Answers/TextAreaAnswer/__snapshots__/TextAreaAnswer.test.js.snap
- src/components/Answers/TextAreaAnswer/index.js
- yarn.lock
Introduced a new component called `BasicAnswer` which encapsulates all of the common fields used in all the basic answer types.
Refactored `TextAnswer`, `TextAreaAnswer`, `CurrencyAnswer` and `NumberAnswer` to use the `BasicAnswer` type.
Updated all affected snapshot and unit tests.
All tests should pass.
Components should still render correctly in storybook.
> Refactor all basic answers to reuse same base component.

- package.json
- src/graphql/answerFragment.graphql
- src/graphql/createQuestionPage.graphql
- src/graphql/createQuestionnaire.graphql
- src/graphql/createSection.graphql
- src/graphql/deleteAnswer.graphql
- src/graphql/deleteOption.graphql
- src/graphql/deletePage.graphql
- src/graphql/deleteQuestionnaire.graphql
- src/graphql/fragments/answer.graphql
- src/graphql/fragments/option.graphql
- src/graphql/fragments/page.graphql
- src/graphql/fragments/questionnaire.graphql
- src/graphql/fragments/section.graphql
- src/graphql/getQuestionnaire.graphql
- src/graphql/getQuestionnaireList.graphql
- src/graphql/getSection.graphql
- src/graphql/pageFragment.graphql
- src/graphql/questionnaireFragment.graphql
- src/graphql/sectionFragment.graphql
- src/tests/utils/MockResolvers.js
- yarn.lock
**DEPENDENT ON https://github.com/ONSdigital/eq-author-api/pull/39 BEING MERGED FIRST**
---
Drops usage of `newId` field throughout, now that `id` fields are of correct type
Run tests, check code
> drop usage of newId

- package.json
- src/apollo/createMockNetworkInterface.js
- src/tests/utils/MockDataStore.js
- src/tests/utils/MockResolvers.js
- yarn.lock
Fixes an error when navigating to the admin page when running with the mockAPI.
The fix involved specifying a reducer for the scalar GraphQL Date type and ensuring that time values do not make it into the localStorage data store.
Should no longer see the error on the admin page after creating a questionnaire when running with the mockAPI.
> Fix error observed on admin page when running with the mockAPI.

- src/components/QuestionnaireNav/SectionNav.js
- src/components/QuestionnaireNav/SectionNav.test.js
- src/components/QuestionnaireNav/SectionNavItem.js
- src/components/QuestionnaireNav/SectionNavItem.test.js
- src/components/QuestionnaireNav/SectionTitle.js
- src/components/QuestionnaireNav/SectionTitle.test.js
- src/components/QuestionnaireNav/__snapshots__/SectionNav.test.js.snap
- src/components/QuestionnaireNav/__snapshots__/SectionNavItem.test.js.snap
- src/components/QuestionnaireNav/__snapshots__/SectionTitle.test.js.snap
- src/components/QuestionnaireNav/__snapshots__/index.test.js.snap
- src/components/QuestionnaireNav/index.js
- src/components/QuestionnaireNav/index.test.js
- src/containers/enhancers/withCreatePage.js
- src/containers/enhancers/withCreatePage.test.js
- src/containers/enhancers/withCreateSection.js
- src/containers/enhancers/withCreateSection.test.js
- yarn.lock
[Trello](https://trello.com/c/FkGCN5EE/254-focus-on-new-section-when-created-2)
Uses [`scrollIntoView`](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView) to ensure any new items (section or pages) are scrolled into view of the questionnaire nav when added.
Add a variety of sections and pages from different starting scroll positions.
> Focus on new section when created

- src/components/Accordion/__snapshots__/index.test.js.snap
- src/components/Accordion/index.js
- src/components/QuestionnaireNav/PageNav.js
- src/components/QuestionnaireNav/SectionTitle.js
- src/components/QuestionnaireNav/__snapshots__/index.test.js.snap
- src/components/RichTextEditor/index.js
Tidied up some visual snags:
- Change colour of properties accordion titles to main text colour (from pure black).
- Change font-size of accordion title to match elsewhere.
- Fixed some alignment issues in the navigation between labels, icons and their surrounding boxes 
- Fixed some line-height issues in the RTE
- check each change is satisfactory
> Various visual tweaks/fixes

- src/containers/QuestionnaireDesignPage/QuestionnaireDesignPage.js
- src/containers/QuestionnaireDesignPage/__snapshots__/QuestionnaireDesignPage.test.js.snap
This PR removes the properties panel from the right hand side of the Questionnaire Design page.
The panel will be added back once a decision has been made about which properties should be displayed.
Observe that the properties panel is no longer visible.
> Remove the properties panel from questionnaire design page.

- package.json
- yarn.lock
The current version of `react-tooltip` is causing errors in production, this upgrades the version to one compatible with React 16.
App should no longer throw errors in prod (check Netifly build)
> Upgrade react-tooltip to 3.4.0

- package.json
Codecov hasn't been checking coverage because coverage reports weren't being generated. This is due to a version mismatch of `yarn` between our dev machines (`> v1`) and travis (`v0.27.3`). In yarn pre-v1, to pass args to package.json scripts you needed a double-dash separator:
```
yarn test -- --coverage
```
In yarn `> v1`, this separator has been retired:
```
yarn test --coverage
```
In v1 yarn the coverage flag will be forwarded correctly, but in yarn `pre-v1`, it will not. This meant that jest never got the coverage flag, lcov reports were not generated, and therefore codecov not correctly checking/enforcing coverage.
Check the Travis output of this PR. At the very end of the logs will be a call to codecov. If you expand this (using the arrow by line number), you should now see that …
> ensure coverage flag passed to jest correctly

- package.json
- src/components/Accordion/__snapshots__/index.test.js.snap
- src/components/Accordion/chevron.svg
- src/components/Accordion/index.js
- src/components/AnswerProperties/__snapshots__/AnswerProperties.test.js.snap
- src/components/AnswerProperties/index.js
- src/components/Forms/Field/__snapshots__/Field.test.js.snap
- src/components/Forms/Form/index.js
- src/components/Forms/Label/__snapshots__/Label.test.js.snap
- src/components/Forms/Label/index.js
- src/components/PageProperties/__snapshots__/PageProperties.test.js.snap
- src/components/PageProperties/index.js
- src/components/PropertiesPanel/__snapshots__/PropertiesPanel.test.js.snap
- src/components/PropertiesPanel/index.js
- src/components/QuestionnaireMeta/__snapshots__/QuestionnaireMeta.test.js.snap
- src/containers/QuestionnaireDesignPage/QuestionnaireDesignPage.js
- src/containers/QuestionnaireDesignPage/__snapshots__/QuestionnaireDesignPage.test.js.snap
This PR adds a "Properties" header to the right hand side panel.
The word "properties" has been dropped from subsequent sections.
The side panel has been re-introduced into the application in preparation for some of the upcoming stories.
Snapshots have been updated.
A visual inspection of the app to see that the properties heading is displayed above all accordion sections.
> Add properties header to right-hand side panel.

- src/components/Menu/__snapshots__/Menu.test.js.snap
- src/components/ScrollPane/__snapshots__/index.test.js.snap
- src/components/ScrollPane/index.js
- src/containers/ToastContainer/index.js
This PR fixes a few visual glitches with the toast.
- Fixes #259 
- Fixes #260
- Fixes #261  - In addition to z-index had to remove the transparent background on toast messages to prevent text from bleeding through.
Re-test the above defects to confirm they are fixed.
> Fixing visual glitches with new delete/undo toast messages.

- .gitignore
- package.json
- scripts/build-status-page.js
This PR introduces a new `/#/status` route for the author application.
A `Status` component has been introduced which outputs simple text with a status of "OK" and the Git SHA-1 has if supplied.
Build a docker container on this branch using the following command:
```docker build -t onsdigital/eq-author:latest --build-arg APPLICATION_VERSION=$(git rev-parse HEAD) .```
Run the newly built author image pointing at a valid API url e.g.
```docker run -ti -e REACT_APP_API_URL=http://docker.for.mac.localhost:4000/graphql 127328c9b756``` (Replace *127328c9b756* with the image Id for onsdigital/eq-author:latest, which can be found by running `docker images`.
Navigate to the application running on port 3000. Browse to the `/#/status` endpoint.
You should see status OK and the Git SHA-1 hash for …
> Add status page to the Author application.

- .travis.yml
- Dockerfile
- scripts/build-status-page.js
fixes issue with previous attempt.
git revision needs to be grabbed _outside_ of docker container, then injected _into_ container, as an env var, before the status page is generated inside
/shrug
```sh
docker build -t onsdigital/eq-author --build-arg APPLICATION_VERSION=$(git rev-parse HEAD) -f Dockerfile .
docker run -p 3000:3000 onsdigital/eq-author
curl http://localhost:3000/status.json
```
> inject git rev into container before generating status page inside

- src/components/Answers/CurrencyAnswer/__snapshots__/CurrencyAnswer.test.js.snap
- src/components/Answers/CurrencyAnswer/index.js
- src/components/Answers/Dummy/DateRange/__snapshots__/index.test.js.snap
- src/components/Answers/Dummy/DateRange/index.js
- src/components/Answers/Dummy/TextArea/__snapshots__/index.test.js.snap
- src/components/Answers/Dummy/TextArea/index.js
- src/components/Answers/Dummy/TextInput/__snapshots__/index.test.js.snap
- src/components/Answers/Dummy/TextInput/index.js
- src/components/Answers/MultipleChoiceAnswer/index.js
- src/components/Answers/NumberAnswer/__snapshots__/NumberAnswer.test.js.snap
- src/components/Answers/NumberAnswer/index.js
- src/components/Answers/TextAnswer/__snapshots__/TextAnswer.test.js.snap
[Trello card](https://trello.com/c/NPM3FK6y/242-visually-differentiate-input-types)
Added styling to visually differentiate text and number dummy inputs. And make all inputs consistent sizes, colours etc
- Check styling aligns with that on the task
> 242 Visually Differentiate Input Types

- src/components/AnswerTypeSelector/AnswerTypeGrid.js
- src/components/AnswerTypeSelector/AnswerTypeSelector.test.js
- src/components/AnswerTypeSelector/__snapshots__/AnswerTypeSelector.test.js.snap
- src/components/AnswerTypeSelector/index.js
- src/components/EditorSurface/CanvasSection.js
- src/components/Popout/Popout.test.js
- src/components/QuestionPageEditor/__snapshots__/QuestionPageEditor.test.js.snap
- src/components/QuestionPageEditor/index.js
Visual change to separate the panels on the main editing canvas.
Also the add answer button has been re-named to "Add another answer", centered and now spans the entire width of the section as per the new design.
Ensure that the visual changes match the design attached to the trello card.
All existing checks and tests should continue to pass.
> Separate panels on main editing canvas.

- src/components/BaseLayout/__snapshots__/BaseLayout.test.js.snap
- src/components/BaseLayout/index.js
- src/components/MainCanvas/__snapshots__/index.test.js.snap
- src/components/MainCanvas/index.js
- src/components/Nav/__snapshots__/nav.test.js.snap
- src/components/Nav/index.js
- src/components/Nav/nav.test.js
- src/containers/QuestionnaireDesignPage/QuestionnaireDesignPage.js
- src/containers/QuestionnaireDesignPage/__snapshots__/QuestionnaireDesignPage.test.js.snap
Move the tabs into the main editing canvas. Previously the tabs occupied their own toolbar which was taking up precious screen real-estate.
This PR moves the tabs down into the main editing canvas. Routing tab does not exist at the moment.
Updated the relevant snapshots.
All checks and tests should pass.
Visually inspect that tabs are now appearing in the main editing canvas and matches the design on the Trello card.
> Move tabs into the main canvas and update snapshots.

- .codecov.yml
We have a high level code coverage, and codecov is currently configured to expect a constant upwards trend. It is more reasonable and practical to have a lower bound, combined with a threshold, so small dips are permissible but we keep coverage high.
Ensure configuration is reasonable and codecov passes
> Tweak codecov config - 90% target, 0.25% threshold

- src/components/NavigationSidebar/SectionNavItem.js
To change the style of the nav bar to bring the focus style of the add question button into line with the rest of the nav bar focus styles.
Should pass all tests and the focus style of the add question button should look the same as the page link focus styles. 
Also this blue line should no longer exist.
> Fixed the focus style issue on the add question button.

- config/webpack.config.common.js
- config/webpack.config.dev.js
- config/webpack.config.prod.js
The webpack config files for both dev and prod had a large amount of duplicated code, this PR is intended to export as much of this common code as possible to both clean up the files and allow for expansion if necessary. 
App should be able to be built in both prod and dev while having a minimum amount of duplicated code, and all smoketests should pass on it.
> 218-improve-webpack-configs

- cypress/integration/author_spec.js
- src/__snapshots__/index.test.js.snap
- src/components/Header/__snapshots__/Header.test.js.snap
- src/components/Header/index.js
- src/components/UserProfile/__snapshots__/index.test.js.snap
- src/components/UserProfile/index.js
- src/containers/QuestionnairesPage/index.js
- src/tests/utils/MockDataStore.js
The user's display name wasn't being supplied when creating a questionnaire, so it would be displayed as "Unknown" when listing questionnaires.
Unfortunately it's difficult/impossible to write a unit test for this. I added a test to our cypress suite to cover this instead.
The basic fix was to pull the user from the store in the `QuestionnairesPage` container. To get the test passing with mock API I needed to also modify the `MockDataStore` as it didn't support createdBy. This test passes with both mock and real API.
Tests pass, code looks good
> Fix missing "created by" on Questionnaires list page

- cypress/integration/author_spec.js
Cypress tests were broken: "should show questionnaire on listing page" was selecting all questionnaire elements on the page so broke when run on a application with more than one questionnaire saved.
Cypress tests should pass both locally and on Travis
> Fixed the broken Cypress test

- cypress/integration/author_spec.js
- src/components/QuestionPageEditor/MetaEditor.js
- src/components/QuestionPageEditor/__snapshots__/MetaEditor.test.js.snap
Fixes bug where question guidance would not be persisted to API. Adds test to prevent regression.
Change looks good, tests pass
> Fix guidance not being persisted to API

- src/components/Answers/MultipleChoiceAnswer/MultipleChoiceAnswer.story.js
- src/components/Answers/MultipleChoiceAnswer/MultipleChoiceAnswer.test.js
- src/components/Answers/MultipleChoiceAnswer/Option.js
- src/components/Answers/MultipleChoiceAnswer/Option.test.js
- src/components/Answers/MultipleChoiceAnswer/__snapshots__/MultipleChoiceAnswer.test.js.snap
- src/components/Answers/MultipleChoiceAnswer/__snapshots__/Option.test.js.snap
- src/components/Answers/MultipleChoiceAnswer/index.js
- src/components/WrappingInput/index.js
It was identified that being able to press the ENTER key when adding Checkbox/Radio options would help to improve the user experience.
This PR enables changes Checkbox and Radio answers so that pressing the ENTER key adds a new Option and brings the new option into focus.
All existing tests and checks should pass.
Have a play around to make sure it behaves as expected.
Pressing the ENTER key in other fields should not add new answers.
> Enable pressing ENTER to add additional options.

- src/components/Answers/MultipleChoiceAnswer/__snapshots__/MultipleChoiceAnswer.test.js.snap
- src/components/Answers/MultipleChoiceAnswer/index.js
Fixes #313 
`MultipleChoiceAnswer` was requiring `onUpdate` prop and passing to `BasicAnswer`. This prop isn't needed as it's provided by `withEntityEditor`.
- test pass
- check the label/description fields of Radio/Checkbox answers work as expected
> issue-313 Fix prop warning in MultipleChoiceAnswer

- src/components/Answers/MultipleChoiceAnswer/Option.js
- src/components/Answers/MultipleChoiceAnswer/__snapshots__/Option.test.js.snap
The label and the delete option buttons overlapped on their focus styles a bit too much, this pr give a more even whitespace to both.
Test should pass and the delete option button should look a lot more reasonable.
> Fixes #307

- src/components/NavigationSidebar/SectionTitle.js
- src/components/NavigationSidebar/__snapshots__/SectionTitle.test.js.snap
This PR fixes #306 and where the section title wasn't being correctly truncated. As seen here:
The section title should now truncate correctly and tests should continue to pass.
> Fixes section title not being truncated in navigation

- cypress/integration/author_spec.js
- package.json
- src/components/AnswerEditor/__snapshots__/answereditor.test.js.snap
- src/components/Answers/DateRange/__snapshots__/index.test.js.snap
- src/components/Answers/DateRange/index.js
- src/components/Answers/DateRange/index.test.js
- src/containers/enhancers/withCreateAnswer.js
- src/graphql/createAnswer.graphql
- src/graphql/fragments/answer.graphql
- src/graphql/getAnswers.graphql
- yarn.lock
Added a secondary label to the basic answer queries and made the relevant front-end changes to allow users to input a from and to label on date ranges.
Tests should pass and user inputted values for Date range label should show up in the publisher json.
Dependencies: 
- ~ONSdigital/eq-author-graphql-schema#28~,
- ONSdigital/eq-author-api#61,
- ONSdigital/eq-publisher#53
> Added secondary label to allow date ranges to have labels

- src/components/MovePageModal/__snapshots__/index.test.js.snap
- src/components/MovePageModal/index.js
- src/components/MovePageModal/index.test.js
This PR modifies MovePageModal so that selections are reset once section/position modal is closed. For example: open section modal, select a section, click "cancel" button. The selection should return back to what it was before opening the modal. 
This PR also includes a slight accessibility improvement: using an actual `label` for the modal trigger (and associating them with each other, via `for`/`id` attributes)
Changes look good
> 390 move page modal improvements

- src/components/Popout/index.js
- src/components/SplitButton/Dropdown.js
- src/components/SplitButton/MenuButton.js
- src/components/SplitButton/MenuItem.js
- src/components/SplitButton/PrimaryButton.js
- src/components/SplitButton/SplitButton.story.js
- src/components/SplitButton/SplitButton.test.js
- src/components/SplitButton/__snapshots__/SplitButton.test.js.snap
- src/components/SplitButton/chevron.svg
- src/components/SplitButton/index.js
This PR introduces a SplitButton component.
The split button is just a wrapper which applies styles to a button and a Popout component. It is required as part of the acceptance criteria for the add "other" option for checkbox and radio Answers.
The split button component can be viewed in Storybook.
A code review is required and all existing tests and checks should pass.
> Add split button component.

- .travis.yml
What is the context of this PR?
Travis seems to generate its own lockfile instead of using the one in the github repo. Which means tests can pass on travis but not be up to date when run locally.
How to review
Travis should fail if the lock-file is out of date with the package.json file and should pass if the inverse is true.
> Added frozen-lockfile flag to travis install step

- src/__snapshots__/index.test.js.snap
- src/graphql/createQuestionnaire.graphql
- src/graphql/getQuestionnaireList.graphql
- src/graphql/undeletePage.graphql
- src/graphql/undeleteQuestionnaire.graphql
- src/redux/undelete/undeletePage.js
- src/redux/undelete/undeletePage.test.js
- src/redux/undelete/undeleteQuestionnaire.js
- src/redux/undelete/undeleteQuestionnaire.test.js
Pages and Questionnaires would be inserted at incorrect position when un-deleting. This PR fixes that.
* Code looks good
* Tests pass
* After moving a page, then deleting a page, then undoing deletion of page, the page is returned to the correct position
* After deleting a questionnaire, and undoing deletion, the questionnaire should return to the correct place in the list (ordered by creation date DESC)
Fixes #349
> Fix undelete position

- scripts/run_e2e_tests_author.sh
https://trello.com/c/OOHsXJKu/187-record-cypress-tests
- adds the `--record` flag to the `run_e2e_tests_author` script
- `CYPRESS_RECORD_KEY ` has been added to travis env vars
- check e2e tests show up in Cypress 'Runs'
> eq-187 Record cypress runs on Travis

- src/components/Header/index.js
- src/components/IconText/index.js
- src/components/MovePageModal/ItemSelect.js
- src/components/MovePageModal/__snapshots__/ItemSelect.test.js.snap
- src/components/MovePageModal/__snapshots__/index.test.js.snap
- src/components/MovePageModal/index.js
- src/components/NavigationSidebar/PageNavItem.js
- src/components/NavigationSidebar/SectionNavLink.js
- src/components/NavigationSidebar/__snapshots__/PageNavItem.test.js.snap
- src/components/SignInForm/GuestSignInForm.js
- src/components/ToggleChip/__snapshots__/ToggleChip.test.js.snap
- src/components/ToggleChip/index.js
- src/components/Truncated/index.js
- src/containers/QuestionnairesPage/QuestionnaireLink.js
- src/containers/QuestionnairesPage/QuestionnairesTable.js
- src/containers/QuestionnairesPage/QuestionnairesTables.test.js
- src/containers/QuestionnairesPage/__snapshots__/QuestionnaireLink.test.js.snap
- src/containers/QuestionnairesPage/__snapshots__/QuestionnairesTables.test.js.snap
The Questionnaires listing previoulsy had flexible columns, and we didn't truncate text in the Created By column. This meant that usernames could awkwardly wrap, as seen below
* Code looks good
* Tests pass
* Table handles long title and long user names
* Check truncation works correctly throughout app (since there is now a single component for this purpose)
**Before**
**After**
**TODO**
Fixes #347
> Fixed table column widths

- src/components/SplitButton/MenuItem.js
After some feedback on the add other option functionality, it became clear that there wasn't a big enough visual distinction to show that the menu option becomes disabled.
I have added a tweak to the styles below so that non-disabled menu items have a pointer cursor (to br consistent with other buttons) and to remove the hover/focus style for disabled split button menu items.
Style changes should indicate more clearly that the add other option menu item becomes disabled after adding an other option.
> Improve UX around disabled split button menu items.

- scripts/run_e2e_tests_author.sh
I ran into an issue when running the e2e tests locally where the tests were being run against an outdated version of the API. The potential for this happening probably warrants
warrants that we do an explicit pull to get the latest images.
Changes should look sensible.
> Pull latest docker images for e2e tests.

- src/components/Answers/BasicAnswer/BasicAnswer.test.js
- src/components/Answers/BasicAnswer/index.js
- src/components/Answers/MultipleChoiceAnswer/Option.js
- src/components/Answers/MultipleChoiceAnswer/Option.test.js
- src/components/Answers/MultipleChoiceAnswer/__snapshots__/MultipleChoiceAnswer.test.js.snap
- src/components/Answers/MultipleChoiceAnswer/__snapshots__/Option.test.js.snap
- src/components/Answers/MultipleChoiceAnswer/index.js
We would previously autofocus on the `MultipleChoiceAnswer`'s Label field, but this is optional and rarely used. It is more convenient for user if the `Option`'s Label field is autofocused, as this aligns with the typical author workflow
Code good, tests pass, behaviour is as described
> autofocus on Option when adding a new MultipleChoiceAnswer

- src/components/Answers/MultipleChoiceAnswer/__snapshots__/Option.test.js.snap
- src/components/WrappingInput/__snapshots__/index.test.js.snap
- src/components/WrappingInput/index.js
On Windows, a scrollbar was shown on the autoresize textarea, causing it not to grow with the content. This PR fixes that.
Change looks good, tests pass, confirmed that bug is fixed on Windows and hasn't introduced issues on OSX
> hide scrollbars on autoresize textarea

- src/components/Button/__snapshots__/index.test.js.snap
- src/components/Button/index.js
- src/components/UserProfile/index.js
Removed inner border from focus style of tertiary buttons.
Before
After
- Check border is removed
> Tweak button styles

- src/components/NavigationSidebar/PageNavItem.js
- src/components/NavigationSidebar/PageNavItem.test.js
- src/components/NavigationSidebar/__snapshots__/PageNav.test.js.snap
- src/containers/App/__snapshots__/index.test.js.snap
- src/custom-prop-types/index.js
- src/utils/UrlUtils.js
It would be more convenient for users if the selected tab (builder or routing) was preserved when navigating between pages. This PR adds such a feature
Code looks good. Feature works as described
> persist selected tab when navigating between pages

- package.json
- src/components/RichTextEditor/index.js
- src/components/RichTextEditor/utils/mapControlsToFilterConfig.js
- src/components/SectionEditor/index.js
- yarn.lock
There was a bug where the Rich text editors weren't stripping out unsupported styles meaning that you could get styles like a list bullet stuck in the editor. This PR adds a filter package to filter out unwanted styles.
Try pasting a bullet list into the description or title boxes and make sure that the unwanted styles are not present.
> Added a style filter to the RTE's

- src/components/QuestionPageEditor/index.js
- src/components/QuestionPageRoute/index.js
- src/components/SectionRoute/index.js
This fixes the issue where the internal state of the `RichTextEditor` falls out of sync with the its props. 
There are other approaches such as using `getDerivedStateFromProps`, but they are more complex. This is a simple solution, which is [recommended by the React docs](https://reactjs.org/docs/react-component.html#static-getderivedstatefromprops):
> If you want to “reset” some state when a prop changes, consider either making a component fully controlled or **fully uncontrolled with a key** instead
Fixes #372 
See #372
Bug no longer reproducible
> use key prop at route level to force new RichTextEditor instances

- package.json
- yarn.lock
Upgrades Cypress from `^2.1.0` to `3.0.2` to fix the issue with the UI jumping around during tests.
- tests pass
- UI no longer jumpy when tests are running
> upgrade cypress to 3.0.2

- cypress/integration/author_spec.js
- cypress/integration/properties_spec.js
- cypress/utils/index.js
- package.json
- src/components/AnswerProperties/AnswerProperties.test.js
- src/components/AnswerProperties/__snapshots__/AnswerProperties.test.js.snap
- src/components/AnswerProperties/index.js
- src/components/AnswerProperties/story.js
- src/components/Answers/BasicAnswer/__snapshots__/BasicAnswer.test.js.snap
- src/components/Answers/MultipleChoiceAnswer/__snapshots__/Option.test.js.snap
- src/components/Forms/Field/__snapshots__/Field.test.js.snap
- src/components/Forms/Label/__snapshots__/Label.test.js.snap
- src/components/Forms/Label/index.js
- src/components/Forms/Number/__snapshots__/numberinput.test.js.snap
- src/components/Forms/Number/index.js
- src/components/Forms/Number/numberinput.test.js
- src/components/Forms/story.js
- src/components/Forms/withChangeHandler.js
- src/components/PropertiesPanel/PropertiesPanel.test.js
- src/components/PropertiesPanel/__snapshots__/PropertiesPanel.test.js.snap
- src/components/PropertiesPanel/index.js
- src/components/QuestionnaireMeta/__snapshots__/QuestionnaireMeta.test.js.snap
- src/components/RichTextEditor/__snapshots__/RichTextEditor.test.js.snap
- src/containers/enhancers/withCreateAnswer.js
- src/graphql/fragments/answer.graphql
- yarn.lock
This is part of a wider piece of work to introduce answer properties to help the quality of the respondent's input.  
Prior to this work, the concept of answer properties was limited to capturing whether or not an answer is 'mandatory'.  This concept has been refactored to support multiple properties and this PR specifically introduces 'decimal' properties.
[Trello Ticket](https://trello.com/c/f978JRq6/402-properties-decimals-1) 
This PR works in conjunction with the following PR's:
API - https://github.com/ONSdigital/eq-author-api/pull/88
Schema - https://github.com/ONSdigital/eq-author-graphql-schema/pull/46
- Run Tests
- Manually create new answers and ensure UI appears as per attached screenshot.
> Display answer properties

- src/components/QuestionPageEditor/MetaEditor.js
- src/components/QuestionPageEditor/__snapshots__/MetaEditor.test.js.snap
The wording of the Guidance label was confusing to some so this pr changes the wording from 'Guidance' to 'Include and exclude guidance' 
Labels changed correctly, tests pass, new wording makes sense.
> Changed the wording of the guidance label

- cypress/integration/author_spec.js
- src/components/Answers/BasicAnswer/BasicAnswer.test.js
- src/components/Answers/BasicAnswer/__snapshots__/BasicAnswer.test.js.snap
- src/components/Answers/BasicAnswer/index.js
- src/components/Answers/CurrencyAnswer/__snapshots__/CurrencyAnswer.test.js.snap
- src/components/Answers/CurrencyAnswer/index.js
The Description for TextField, TextArea and Number answers weren't showing in Runner as the Runner templates do not currently support these fields. This Pr disables description inputs for those answers to prevent user confusion.
Tests pass and Description inputs should only be visible on the following answer types: Currency, Radio and Checkbox.
> Prevented description from showing for some answers

- cypress/integration/author_spec.js
- cypress/utils/index.js
- package.json
- src/components/QuestionPageRoute/index.test.js
- src/components/SectionRoute/Section.graphql
- src/components/SectionRoute/index.js
- src/components/SectionRoute/index.test.js
- src/containers/enhancers/withCreateSection.js
- src/containers/enhancers/withCreateSection.test.js
- src/containers/enhancers/withDeleteSection.js
- src/graphql/createSection.graphql
- src/graphql/deleteSection.graphql
- src/graphql/getQuestionnaire.graphql
- src/graphql/questionnaireFragment.graphql
- yarn.lock
- Disables 'Move Section' button when there is only one section in a questionnaire
- https://trello.com/c/18p5lgJP/533-disable-move-section-button-if-there-is-only-one-section
- Run Tests 
- Ensure button is correctly disabled and enabled
- https://github.com/ONSdigital/eq-author-api/pull/97
> Disable move section button based on number of sections 

- cypress/integration/author_spec.js
- package.json
- src/components/SectionEditor/__snapshots__/SectionEditor.test.js.snap
- src/components/SectionEditor/index.js
- src/graphql/fragments/section.graphql
- yarn.lock
- Upgrades graphql schema which deprecates section description field as it is redundant and never used by eq-runner
- Stops displaying section description content when creating a questionnaire
- Run tests
GraphQL Schema - https://github.com/ONSdigital/eq-author-graphql-schema/pull/51
> Remove redundant section description field

- package.json
- src/components/Forms/Field/__snapshots__/Field.test.js.snap
- src/components/Forms/Input/__snapshots__/Input.test.js.snap
- src/components/Forms/Input/index.js
- src/components/Forms/Number/__snapshots__/numberinput.test.js.snap
- src/components/QuestionnaireMeta/__snapshots__/QuestionnaireMeta.test.js.snap
- src/components/ToggleSwitch/__snapshots__/toggleswitch.test.js.snap
- src/components/Typeahead/TypeaheadMenu.js
- src/components/Typeahead/__snapshots__/test.js.snap
- src/components/Typeahead/index.js
- src/components/Typeahead/story.js
- src/components/Typeahead/test.js
- yarn.lock
[Trello card](https://trello.com/c/POnn9CQN/483-survey-data-typeahead-component)
Adds `Typeahead` component that takes a list of objects with values and handles the filtering of those values according to user input as well as the dropdown menu displaying options for selection.
This component uses [Downshift](https://github.com/paypal/downshift) and exposes two components: 
- `Typeahead` exposes a Downshift component and simply handles mapping `onChange` and `itemToString` props, the latter handles the mapping of `value` of items into strings.
- `TypeaheadMenu` contains logic for filtering menu items by user input and all the styling associated with the menu and items.
A11y concerns are handled by Downshift itself.
- Check component works in storybook
- Tests pass
> Typeahead component

- src/components/EditorLayout/index.js
- src/components/MainCanvas/__snapshots__/index.test.js.snap
- src/components/MainCanvas/index.js
- src/components/QuestionnaireDesignPage/__snapshots__/QuestionnaireDesignPage.test.js.snap
- src/components/QuestionnaireDesignPage/index.js
Increases the width of the navigation and properties sidebars.
- Run tests
- Ensure width of sidebars and content are consistent between views (eg. Question Editor / Routing etc.)
> Make navigation and properties sidebars wider

- src/components/Answers/Dummy/Date/index.js
- src/components/Answers/Dummy/Date/placeholder.svg
- Fixes style of dummy radio button (see screenshot)
- Caused by: https://github.com/ONSdigital/eq-author/pull/399
- Run Tests
- Ensure style of radio answers and date answers are as expected
> Fix Radio Button Styles

- src/components/RichTextEditor/RichTextEditor.test.js
- src/components/RichTextEditor/index.js
- src/components/withEntityEditor/index.js
- src/components/withEntityEditor/index.test.js
- Fixes an error caused by setting the state on unmounted components which indicates a memory leak
- Fixes https://github.com/ONSdigital/eq-author/issues/397
- We suspect this was contributing to our Cypress tests becoming slow, unpredictable and flakey
- Run Tests
- Run Cypress tests, open browser console and ensure there are no errors
- Use steps described in https://github.com/ONSdigital/eq-author/issues/397
> Fix setState being called on unmounted component. Issue #397

- src/components/AnswerEditor/index.js
- src/components/Answers/Date/index.js
- src/components/Answers/DateRange/__snapshots__/index.test.js.snap
- src/components/Answers/DateRange/index.js
- src/components/Answers/Dummy/Date/__snapshots__/index.test.js.snap
- src/components/Answers/Dummy/Date/index.test.js
There is small visual bug where the date range type was not correctly displaying the dummy data entry. This Pr fixes that issue by adding an extra prop type that can override the others. 
Tests pass and the date range answer displays correctly and the date properties can also be correctly changed.
> Fixed visual bug

- cypress/integration/authenticated/builder_spec.js
Issue in the cypress test, from the mutually exclusive answer PR. After testing the cypress tests an only had been left in the code meaning that it would be the only test that was being run.
All cypress test pass and all cypress tests run.
> Removed only condition from cypress tests

- cypress/.eslintrc
- cypress/fixtures/answers/ToggleValidationRule.js
- cypress/fixtures/answers/createDateAnswer.js
- cypress/fixtures/answers/date/updateValidationRule.js
- cypress/integration/authenticated/validation_spec.js
- cypress/support/commands.js
- package.json
- src/components/Answers/BasicAnswer/index.js
- src/components/Validation/AnswerValidation.js
- src/components/Validation/AnswerValidation.test.js
- src/components/Validation/EarliestDate.js
- src/components/Validation/EarliestDate.test.js
- src/components/Validation/__snapshots__/AnswerValidation.test.js.snap
- src/components/Validation/__snapshots__/EarliestDate.test.js.snap
- src/components/Validation/path-end.svg
- src/components/Validation/path.svg
- src/components/Validation/withAnswerValidation.js
- src/components/Validation/withAnswerValidation.test.js
- src/components/withEntityEditor/index.js
- src/components/withEntityEditor/index.test.js
- src/containers/enhancers/withToggleAnswerValidation.js
- src/containers/enhancers/withUpdateAnswerValidation.js
- src/graphql/createAnswer.graphql
- src/graphql/fragments/earliest-date-validation-rule.graphql
- yarn.lock
This change implements updating earliest date validation for `Date` answers.
1. Add a Date answer to a page.
2. Ensure you can enable it and update all the fields in the modal that is opened.
> 449 - Earliest date validation

- .nvmrc
Specify to use node carbon to:
1. Set netlify to use the correct node version when building
2. Set correct node version locally
1. Ensure that in the netlify deploy logs for this PR that it uses node 8.12.0
2. That with nvm installed correctly that when you switch into the directory that your node version switches to 8.12.0
> Specify node version for NVM

- package.json
- src/components/Button/__snapshots__/index.test.js.snap
- src/components/ContentPicker/__snapshots__/ContentPickerSingle.test.js.snap
- src/components/Dialog/DialogIcon/__snapshots__/DialogIcon.test.js.snap
- src/components/Menu/SubMenuItem.js
- src/components/Tabs/__snapshots__/tabs.test.js.snap
- yarn.lock
- Hot reloading has stopped working when editing styled components
- Upgraded `styled-components` package to fix this
- Upgraded `jest-styled-components` package to support `styled-components` upgrade
- Fixed a warning relating to `.extend` being deprecated in upcoming `styled-components` v4 release
- Run tests
- Ensure styles are the same
- Ensure you can edit a styled component and it triggers a reload
> Fix styled component modifications failing to trigger hot reload

- cypress/integration/authenticated/metadata_spec.js
- src/components/MetadataTable/Controls/KeySelect.js
The type-ahead in the metadata table is currently allowing users to set keys like exp which is used in the generation of the JWT meaning that users could get in a very broken state where the JWT could expire before it could be used.
Tests should continue to pass and users should no longer see the problematic keys in the typeahead.
> Removed problematic metadata keys from the type ahead

- src/components/Header/index.js
This PR adds the ability to handle the go-launch env var being null so that we can gracefully switch over from using GLAS to our own api endpoint.
Tests pass all existing behaviour is intact.
> Changed the link generated for preview surveys to not use go-launch 

- src/components/Validation/MaxValue.js
- src/components/Validation/MaxValue.test.js
- src/components/Validation/MinValue.js
- src/components/Validation/MinValue.test.js
After graphql was updated to to the latest version a bug was introduced where the api no-longer coerced string int values into actual in values and instead it threw an error. This PR changes that so it now imports int values instead.
Tests pass and min and max values can be changed.
> Switched min/max values to use ints instead

- scripts/run_e2e_tests_author.sh
A recent change has led to noisy log output when running the cypress tests.
This PR reverts the specific change and runs the API docker containers in detached mode during the Cypress tests.
Observe travis log output to ensure that API HTTP logs are not displayed.
> Prevent noisy logging during cypress tests

- .dockerignore
- Dockerfile
- README.md
- docker-entrypoint.sh
- nginx/docker-entrypoint.sh
- nginx/mime.types
- nginx/nginx.conf
- nginx/replace_env_vars.sh
- nginx/sites-enabled/eq-author
- public/index.html
- scripts/test_docker-compose.yml
- src/auth/index.js
- src/components/Header/Header.test.js
- src/components/Header/index.js
- src/config.js
- src/index.js
- src/redux/auth/actions.js
- src/redux/auth/actions.test.js
Change the way we build the UI docker image so that:
1. It does not build every time you run it (to be updated for the new environment variables)
1. Make the image significantly smaller as it just contains the build output and the nginx configuration.
1. Runtime environment variables passed to docker are still applied. 
1. Only `NODE_ENV` and `REACT_APP_ENABLE_AUTH` are determined when the docker image is built. Both are either hardcoded or picked up automatically as part of the `.env.production`.
1. Image size now: 124MB from 1.77GB
1. Image start time 2-3 seconds from >80 seconds
1. Ensure you can build and run the built image locally.
> Tech debt stop ui repeatedly building

- config/webpack.config.common.js
As part of an unintentional bump of the storybook version in
e8f9c1dfc6c143c834d11bf68d8070cb3597b68e (#452) it would no longer run
correctly.
The issue was already reported and relates to our webpack config
derived from CRA. https://github.com/storybooks/storybook/issues/2615
1. Upgrade your modules by running `rm -rf node_modules && yarn --frozen-lockfile`
1. Ensure you can run storybook locally
> Bug - Storybook upgrade broke with our webpack config

- src/components/Validation/Date/builder.js
- src/components/Validation/Date/builder.test.js
The lint rule of no unused vars caused the way this was working to be
removed (e8f9c1d) and the tests were not explicitly testing this usecase.
1. Ensure you can update an earliest/latest date validation
> Bug - Unable to update date validation

- cypress/support/commands.js
- cypress/utils/index.js
- src/components/Toast/__snapshots__/index.test.js.snap
- src/components/Toast/index.js
Trigger all toasts to be dismissed after answer deletion
This speeds up `properties_spec` from 3:15min on my local to 0:45min.
CI `test:integration` reduced by 5 mins:
- Before ~1100 seconds: 
- [Example 1](https://travis-ci.org/ONSdigital/eq-author/builds/440668200)
- [Example 2](https://travis-ci.org/ONSdigital/eq-author/builds/440668440)
- After ~800 seconds 
- [Example 1](https://travis-ci.org/ONSdigital/eq-author/builds/441576602)
1. Ensure that cypress still passes for you locally.
1. Ensure that `properties_spec` is faster for you.
> Tech Debt - Slow cypress waiting for toast

- cypress/plugins/index.js
- Adds `cypress/plugins/index.js` template file back into the repository as it keeps on reappearing when running `yarn install`
- `eslint-disable-next-line` has been added to ensure linting still passes
- Run tests
> Add cypress plugins template file

- cypress/integration/authenticated/routing_spec.js
- src/components/routing/RoutingCondition.js
A bug was found where if a user creates a date answer then goes to create a routing rule on that same question then the routing rule question selector would default to that question instead of null leading to a bad routing rule which would end in an error being thrown by Publisher. 
The bug cannot be re-created and the new test to ensure the bug has been fixed, passes.
> Fixed bug that would occur when creating a rule on unsupported answer.

- src/components/routing/NumberAnswerSelector.js
- src/components/routing/__snapshots__/NumberAnswerSelector.test.js.snap
Due to Runner limitations we were not able to include the inclusive comparators on the first pass of routing based on a number. This has since been resolved so this PR adds that functionality. 
Tests pass and you are able to publish a survey with an inclusive comparator in the routing conditions.
> Added inclusive number options to routing

- cypress/integration/authenticated/builder_spec.js
- src/components/AnswerEditor/__snapshots__/answereditor.test.js.snap
- src/components/AnswerEditor/index.js
Number answer description re enabled because Runner now supports it
- Run tests
- Make sure description appears on number answers
> Add description field on numeric answer types.
