src/components/QuestionForm.js, src/components/TextArea.js, src/reducers/question.js
Added <textarea> to author prototype 
##How to review
Check <textarea> has been added to the form
=> Added textarea

src/components/QuestionForm.js
This PR adds the question title and guidance title fields to the question form.
Launch the eq-author prototype.
Observe that both fields are present.
Ensure that they have the correct default values and name/Id.
Ensure that code adheres to best practices/conventions.
=> Adds the question title and guidance title fields.

src/components/QuestionForm.js, src/components/TextArea.js
This PR adds a `textarea` component for entering the question guidance.
Launch the eq-author prototype.
Observe that the textarea is present.
Ensure that they have the correct default values and name/Id.
Ensure that code adheres to best practices/conventions.
=> Adds textarea component for question guidance.

src/components/JsonWindow.css, src/components/JsonWindow.js, src/components/QuestionForm.js, src/containers/JsonWindow.js, src/reducers/question.js
Wired up JSON textarea to state so it displays the JSON 
Related issue #4 
Check json window is wired up correctly
=> Wire up JSON textarea to state so it displays the JSON

package.json, src/components/Checkbox.js, src/components/QuestionForm.js, src/components/RichTextArea.css, src/components/RichTextArea.js, src/components/Select.js
This PR adds response fields to the authoring tool.
=> Adds response fields to authoring tool.

package.json, src/actions/index.js, src/components/GuidanceFields.js, src/components/QuestionForm.js, src/containers/JsonWindow.js, src/reducers/question.js, yarn.lock
=> moved guidance into its own bit of state and components

src/actions/index.js, src/components/Checkbox.js, src/components/Input.js, src/components/Link.js, src/components/OptionsInputList.css, src/components/OptionsInputList.js, src/components/QuestionForm.js, src/components/ResponseFields.js, src/components/ResponseList.js, src/components/RichTextArea.js, src/containers/QuestionForm.js, src/reducers/question.js
Fixes #7.
This PR adds rendering of JSON for the response fields.
=> Wire up answers to update the JSON window.

data/2_0001.json, package.json, src/components/Checkbox.js, src/components/QuestionForm.js, src/components/ResponseFields.js, src/containers/QuestionForm.js, src/index.js, src/reducers/question.js, yarn.lock
Fixes #15 by using local storage to store the Redux store. This allows for changes in Question and Answer state to be persisted between sessions.
=> Store data between sessions

src/components/AnswerFields/index.js
Fixes #24.
Validation message component on subsequent answers doesn't update the JSON schema.
Modify the default JSON so that it includes multiple answers.
Enter text in both validation message fields and observe that the JSON updates appropriately.
=> Fixes validation message fields don't update JSON window correctly

src/components/AnswerFields/index.js, src/components/OptionsInputList/index.js, src/components/QuestionForm/index.js, src/components/ResponseList/index.js, src/components/Tabs/TabList.js, src/components/Tabs/TabPanel.js, src/components/Tabs/TabTitle.js, src/components/Tabs/Tabs.js, src/components/Tabs/index.js, src/components/forms/Input/index.js, src/foundation.css
Fixes #18 
- Added `Tabs` component that is composed of `TabList`, `TabTitle` and `TabPanel`.
=> Implement tabs

src/components/AnswerList/index.js, src/components/App/index.js, src/components/GuidanceFields/index.js, src/components/JsonWindow/index.js, src/components/Link/index.js, src/components/ResponseList/index.js, src/components/forms/Checkbox/index.js, src/components/forms/Field/index.js, src/components/forms/Input/index.js, src/components/forms/Label/index.js, src/components/forms/Select/index.js, src/components/forms/TextArea/index.js
Fixes #30. This PR refactors several of the existing components that do not have any internal state to be stateless functions instead.
In theory, any component that would render the same given the same props could be converted into stateless functions to improve performance. In practice, there are a few components that I have left as they were because they have other logic associated with them (event handler logic etc.).
Ensure that the author application still behaves correctly.
Review the code changes and advise on any components that I may have missed.
=> Refactor several components to stateless functions.

src/components/AnswerFields/index.js, src/components/OptionsInputList/index.js, src/components/QuestionForm/index.js, src/components/forms/Field/index.js, src/components/forms/Label/index.js
Fixes #29 `Field` component passes any props it receives to its children.
This allows us to define the `for/id` relationship between input + label more easily.
=> Field component now passes props to children

package.json
##What is the context of this PR?
Added linter
##How to review
Check linter is working correctly. 
Maybe we should install this as a dependancy?
=> added linter

src/actions/answers.js, src/components/Answer/index.js, src/components/Options/index.js, src/containers/Answers.js, src/reducers/answers.js
Fixes #12.
Implements the TextArea version of answer options using one option per line.
=> Answer options TextArea

.travis.yml, yarn.lock
Fixes #32.
This PR aims to automate deployment of a successful build of the Authoring prototype to GitHub pages.
Travis CI will be used to automate the deployment after a successful build.
=> Automate deployment of Authoring Prototype to GitHub pages.

src/index.js
Fixes #62 
Implemented hot reload of components so that saving a component automatically updates the view without having to reload the page whilst preserving application state.
- Edit any component
- You should see changes automatically
=> Add hot reload

src/components/Breadcrumb/chevron.js, src/components/Breadcrumb/index.js, src/components/Breadcrumb/story.js, src/constants/theme.js
This PR adds a breadcrumb component as per the Sketch designs.
**N.B - This pull request is based off the `sidebar-component` branch. Please ensure that the `sidebar-component` branch is merged Before this this branch.**
Take a look at both `Breadcrumb` and `BreadcrumbLink` components in React StoryBook.
=> Adds breadcrumb component

src/components/FileUpload/index.js, src/components/FileUpload/story.js, yarn.lock
This PR fixes issue #48 by allowing them to select a JSON schema to load into the React component tree state.
=> Enables user to load schema file.

src/components/Grid/Column.js, src/pages/survey_create.js
Bit of a tidy up to use the Grid component instead of rolling Yet Another React Component (YARC) for columns.
=> Refactor create survey page to utilise Grid component.

.babelrc, config/env.js, config/jest/cssTransform.js, config/jest/fileTransform.js, config/paths.js, config/polyfills.js, config/webpack.config.dev.js, config/webpack.config.prod.js, package.json, scripts/build.js, scripts/start.js, scripts/test.js, src/components/Button/index.js, src/components/Tabs/TabList.js, src/components/Tabs/TabPanel.js, src/components/Tabs/Tabs.js, src/containers/App.js, src/helpers/fetch.js, src/helpers/index.js, src/helpers/persist.js, src/index.js, src/reducers/index.js, yarn.lock
Re-enabled hot reloading of components to prevent a full page refresh when a component is saved.
- load app
- change a component and save
- page should not refresh but component should update
=> Added hot reload

package.json
Modified the package.json file so that when NPM start is ran yarn is run at the same time
=> Modified yarn to always run on NPM start

src/containers/App.js, src/pages/NotFound.js, src/routes.js
Modified application so that any page which isn't defined comes back with a 404 error
=> Added 404 routing

.travis.yml
- Added `yarn test` command to Travis config
- Runs tests before build to fail early
- Check that current test/s are being run on Travis
- Write a test that fails
=> Add test script to travis config

src/components/Forms/Select/Select.test.js, src/components/Forms/Select/index.js, src/components/Forms/Select/story.js
Firm up implementation of the Select component which is being used currently to display a list of available themes (default, UKIS, Census) to the author.
See the [Trello card](https://trello.com/c/I51C8qso/3-branding-selection-1) for further details.
Review Jest tests.
Review the Storybook scenarios.
All existing tests should continue to pass.
All linting/styling checks should pass.
=> Branding Selection

src/reducers/survey.js
Fixed a bug causing the "Add a section" feature to no longer work
- create an empty survey
- progress to design page
- add a section, give it a name and press enter
- section should be added to list
=> Fix adding section

src/components/Forms/Select/index.js, src/pages/CreateSurvey.js, src/reducers/survey.test.js
Noticed a couple of warnings from linter, and proptype warnings when running tests. This fixes those
Run `yarn test` and `yarn lint`, observe that no errors/warnings logged to console
=> fix proptype and lint warnings

src/components/Link/index.js
This PR simply removes Link component as it is no longer used in the Author application.
All tests should continue to pass and application behaviour should not be changed.
=> Remove Link component

.eslintrc, package.json, src/actions/survey.js, yarn.lock
- Adds a git precommit hook to run prettier on staged files
- `yarn`
- open a file and remove formatting that would be applied with prettier (eg. semicolons)
- stage and commit file/s
- check that prettier reformats staged code
=> Implement prettier precommit hook

README.md
Added a troubleshooting section to readme with solution to problem I just encountered running Jest
Just check it makes sense
=> Update readme with troubleshooting

.codecov.yml, .gitignore, src/components/RichTextArea/richtextarea.test.js, src/components/RichTextArea/story.js
Backfill tests for the rich text area component.
Add story demonstrating different features of the component.
Normal rich text editor functionality is observed.
=> Backfill tests rich text area

src/components/ButtonGroup/__snapshots__/buttongroup.test.js.snap, src/components/ButtonGroup/buttongroup.test.js, src/components/ButtonGroup/story.js
Add tests and story for ButtonGroup component.
All existing tests should pass and application behaviour should be unchanged.
=> Backfill tests for button group component.

.eslintrc, .travis.yml, src/actions/survey/items.js, src/components/HTMLPreview/Answer.js, src/components/HTMLPreview/index.js, src/components/OptionsPanel/index.js, src/components/TreeMenu/TreeMenu.js, src/containers/App.js, src/containers/DesignSurvey.js, src/containers/DesignSurvey.test.js, src/containers/SurveySidebar.js, src/pages/CreateSurvey.js, src/pages/CreateSurvey.test.js, src/pages/DesignSurvey.js, src/pages/DesignSurvey.test.js, src/pages/NotFound.js, src/pages/Survey.js, src/proptypes/answer.js, src/proptypes/index.js, src/proptypes/question.js, src/proptypes/section.js, src/proptypes/survey.js, src/reducers/survey/items.js, src/reducers/survey/items.test.js, src/reducers/survey/meta.js, src/reducers/survey/meta.test.js, src/routes.js
Fixes #125 
- sured up code that passes id's around
- refactored layout out of page components and into route definition to
to make testing easier
- added some tests
As per bug repro steps
=> Fix add a section

src/index.js, src/utils/render.js, src/utils/render.test.js
Hot module replace had been throwing errors, this fixes it
Check that errors aren't thrown by react when HMR happens
=> Correctly render hot-loaded App container

.gitignore, src/components/Nav/__snapshots__/nav.test.js.snap, src/components/Nav/index.js, src/components/Nav/nav.test.js, src/components/Nav/story.js, src/components/Tabs/TabList.js, src/components/Tabs/TabTitle.js, src/components/Tabs/story.js, src/constants/theme.js, src/layouts/sidebarpage.js, src/layouts/tabbedpage.js, yarn.lock
Created new Nav component and added styling to Tabs component
Check Nav component 
Check Nav tests
Check Tab styling
Check storybook for both components
=> Tab styles

src/components/Link/link.test.js
Added the jest test to test the link component
Run "Yarn Test" hit "P" type in "link" and see if the 3 tests pass for the component/link
=> Added jest test for link component

src/components/BaseLayout/__snapshots__/BaseLayout.test.js.snap, src/components/Forms/Field/__snapshots__/Field.test.js.snap, src/components/Forms/Input/__snapshots__/Input.test.js.snap, src/components/QuestionnaireMeta/__snapshots__/QuestionnaireMeta.test.js.snap
Snapshot tests were out-of-date
Run all tests, check they pass
=> Fix snapshot tests

src/components/QuestionnaireMeta/__snapshots__/QuestionnaireMeta.test.js.snap, src/components/QuestionnaireMeta/index.js, src/containers/QuestionnaireCreatePage/QuestionnaireCreate.js, src/queries/createQuestionnaire.js, src/queries/getQuestionnaire.js, src/queries/updateQuestionnaire.js
Added `surveyId` to create questionnaire page. Also adde the `Voluntary` option to `Legal Basis` and removed `Starwars` option from the `Theme` select.
Check the `surveyId` is being sent correctly to graphql and that the new options have been added correctly
=> Added survey id and voluntary option

.env.development
This PR updates the eq-author appolication to point at the updated API endpoint.
Can successfully run Author against the author-api (master)
=> Update the env to point at the new GraphQL api endpoint.

src/components/PropertyPane/PropertyPane.js, src/components/PropertyPane/PropertyPane.test.js, src/components/PropertyPane/PropertyPaneTitle.js, src/components/PropertyPane/PropertyPaneTitle.test.js, src/components/PropertyPane/__snapshots__/PropertyPane.test.js.snap, src/components/PropertyPane/__snapshots__/PropertyPaneTitle.test.js.snap, src/components/PropertyPane/index.js, src/components/QuestionProperties/QuestionProperties.test.js, src/components/QuestionProperties/__snapshots__/QuestionProperties.test.js.snap, src/components/QuestionProperties/index.js, src/components/QuestionProperties/story.js, src/containers/QuestionnaireDesignPage/QuestionnaireDesign.js, src/custom-prop-types/index.js
Added question properties
Navigate to the builder and check question properties looks like designs.
=> Question properties

config/webpack.config.dev.js, config/webpack.config.prod.js, package-lock.json, package.json, yarn.lock
Added svgo
Check SVGs are smaller and have different names both in dev and production
=> added svgo

.eslintrc, package.json, src/components/Header/Header.test.js, src/components/Header/index.js, src/components/Panel/index.js, src/components/Tabs/TabTitle.js, src/helpers/index.js, yarn.lock
This PR adds sensible linting rules for imports and exports to Author.
Linting should pass without warnings/errors.
Build should pass.
Breaking the import/export linting rules should result in an appropriate error and break the build.
=> Add linting rules for imports/exports

src/queries/createPage.js, src/queries/createSection.js, src/queries/getQuestionnaire.js, src/queries/getSection.js, src/queries/updateSection.js
Switches to using 'sections' instead of 'groups' from API
Run tests, ensure all pass. Manually test in browser
=> switch from 'groups' to 'sections'

package.json, src/components/Forms/withChangeHandler.js, src/components/Forms/withChangeHandler.test.js, src/components/Nav/__snapshots__/nav.test.js.snap, src/components/Nav/index.js, src/components/Nav/nav.test.js, src/components/QuestionnaireDesign/QuestionnaireDesign.test.js, src/components/QuestionnaireDesign/__snapshots__/QuestionnaireDesign.test.js.snap, src/components/QuestionnaireDesign/__snapshots__/SeamlessInput.test.js.snap, src/components/QuestionnaireDesign/__snapshots__/SeamlessTextArea.test.js.snap, src/components/QuestionnaireDesign/withSeamlessness.js, src/containers/QuestionnaireCreatePage/QuestionnaireCreatePage.js, src/containers/QuestionnaireCreatePage/QuestionnaireCreatePage.test.js, src/containers/QuestionnaireCreatePage/index.js, src/containers/QuestionnaireCreatePage/index.test.js, src/containers/QuestionnaireDesignPage/QuestionnaireDesignPage.js, src/containers/QuestionnaireDesignPage/QuestionnaireDesignPage.test.js, src/containers/QuestionnaireDesignPage/__snapshots__/QuestionnaireDesignPage.test.js.snap, src/containers/QuestionnaireDesignPage/index.js, src/containers/QuestionnaireMetaPage/index.js, src/queries/createPage.js, src/queries/createQuestionnaire.js, src/queries/getQuestionnaire.js, src/queries/updatePage.js
This adds functionality to Quesitonnaire Designer to edit question title, description, and guidance. It also fixes the questionnaire creation flow to create an initial page by default, otherwise there is no page to edit initially. This can be simplified once the API assumes this repsponsibility (see [this PR](https://github.com/ONSdigital/eq-author-api/pull/19))
Review code, run tests
=> Set Question Title and Description

src/components/IconGrid/IconGrid.js, src/components/IconGrid/IconGrid.test.js, src/components/IconGrid/IconGridButton.js, src/components/IconGrid/IconGridButton.test.js, src/components/IconGrid/IconGridSVG.js, src/components/IconGrid/__snapshots__/IconGrid.test.js.snap, src/components/IconGrid/__snapshots__/IconGridButton.test.js.snap, src/components/IconGrid/icons/checkbox.svg, src/components/IconGrid/icons/currency.svg, src/components/IconGrid/icons/date.svg, src/components/IconGrid/icons/number.svg, src/components/IconGrid/icons/radio.svg, src/components/IconGrid/icons/select.svg, src/components/IconGrid/icons/textarea.svg, src/components/IconGrid/icons/textfield.svg, src/components/IconGrid/icons/time.svg, src/components/IconGrid/index.js, src/components/IconGrid/story.js, yarn.lock
Added icon grid component
Check component matches designs: https://docs.google.com/presentation/d/1D80cOrhRs-p-jCE3nZ1UHPkSyZQVOIeyjpB-5rSzVqA/edit#slide=id.g248faee3f0_1_4
=> Icon grid component

src/components/Button/index.js, src/components/Header/index.js, src/components/IconGrid/IconGridButton.js, src/components/Nav/__snapshots__/nav.test.js.snap, src/components/Nav/index.js, src/components/Popout/story.js, src/components/QuestionnaireDesign/__snapshots__/QuestionnaireDesign.test.js.snap, src/components/QuestionnaireDesign/withSeamlessness.js, yarn.lock
Made font weight's consistent 
Check that `400, 500, 600, 700 and 900` font weights have been replaced with just `400`, `700` and `900`
=> Font weights

package.json
jest has problem finding modules unless you tell it all our imports are relative to the `src/` dir. this updates the config to do that.
run tests ensure they pass still
=> update jest config to allow debugging

.dockerignore, .travis.yml, Dockerfile, docker-entrypoint.sh
I have added a Dockerfile and updated the Travis build to push the images to DockerHub
Build the Docker image `docker build -t onsdigital/eq-author .`
Then run it `docker run -it -p3000:3000 -e REACT_APP_API_URL=http://localhost:4000/graphql onsdigital/eq-author` to see if it works as expected
=> Added Dockerfile and updated build

.eslintrc.js, package.json
Noticed we weren't having linting for graphql files anymore. This fixes that
Purposefully add an error to a graphql file, lint, ensure it complains
=> fix graphql linting

src/components/AnswerProperties/AnswerProperties.test.js, src/components/AnswerProperties/__snapshots__/AnswerProperties.test.js.snap, src/components/AnswerProperties/index.js, src/components/AnswerProperties/story.js, src/components/Forms/Field/index.js
This PR introduces the Answer Properties component.
Should be able to use the answer properties component from within storybook.
=> Add Answer Properties component.

src/components/Answers/CurrencyAnswer/CurrencyAnswer.story.js, src/components/Answers/CurrencyAnswer/CurrencyAnswer.test.js, src/components/Answers/CurrencyAnswer/__snapshots__/CurrencyAnswer.test.js.snap, src/components/Answers/CurrencyAnswer/index.js, src/components/Forms/Field/__snapshots__/Field.test.js.snap, src/components/Forms/Field/index.js, yarn.lock
Added currency answer component 
- Check component against trello task here: https://trello.com/c/asIXePnn/163-add-edit-currency-answer-component-3
- View in storybook
- Run tests
=> Currency answer component

src/components/Answers/NumberAnswer/NumberAnswer.story.js, src/components/Answers/NumberAnswer/NumberAnswer.test.js, src/components/Answers/NumberAnswer/__snapshots__/NumberAnswer.test.js.snap, src/components/Answers/NumberAnswer/index.js
Added number answer component
Check against this trello task: https://trello.com/c/u0tK9TDZ/165-add-edit-number-answer-component-3 
Check Number component in storybook under "AnswerTypes"
Run tests
=> Number answer component

src/components/Answers/CheckboxAnswer/CheckboxAnswer.story.js, src/components/Answers/CurrencyAnswer/CurrencyAnswer.story.js, src/components/Answers/TextAreaAnswer/TextAreaAnswer.story.js, src/components/Answers/TextAreaAnswer/TextAreaAnswer.test.js, src/components/Answers/TextAreaAnswer/__snapshots__/TextAreaAnswer.test.js.snap, src/components/Answers/TextAreaAnswer/index.js
Added `TextAreaAnswer` component
- reorganised the answer component stories into their own "folder" in the storybook
1. Visit storybook and check component works
=> added TextAreaAnswer component

src/graphql/createPage.graphql, src/graphql/getQuestionnaire.graphql, src/graphql/updatePage.graphql
[Trello](https://trello.com/c/WzXFGP4i/110-remove-mandatory-field-from-questions-1)
- removes reference to `mandatory` field from usage of `Question`.
- ensure tests pass
=> 110 Remove mandatory from Question

package.json, src/components/QuestionProperties/QuestionProperties.test.js, src/components/QuestionProperties/__snapshots__/QuestionProperties.test.js.snap, src/components/QuestionProperties/index.js, src/containers/enhancers/withCreatePage.js, src/custom-prop-types/index.js, src/graphql/createPage.graphql, src/graphql/createQuestionPage.graphql, src/graphql/createSection.graphql, src/graphql/getQuestionnaire.graphql, src/graphql/updatePage.graphql, src/tests/utils/MockDataStore.js, yarn.lock
Removes references to `type` field on QuestionType.
Updates to point at latest schema.
Update mock data store with latest schema changes.
All tests should pass.
=> Remove type from questionpage

src/components/AnswerEditor/__snapshots__/answereditor.test.js.snap, src/components/AnswerEditor/index.js, src/components/Answers/MultipleChoiceAnswer/MultipleChoiceAnswer.test.js, src/components/Answers/MultipleChoiceAnswer/index.js
Fixes #206 
Ensure bug is fixed, tests pass, code is good
=> set min Options for Radio answer to 2. fix #206

doc/001-typescript.md
Documents the Flow vs Typescript spike
Check it makes sense, anything else that needs adding?
=> Spike typescript writeup

src/components/AnswerEditor/__snapshots__/answereditor.test.js.snap, src/components/AnswerEditor/answereditor.test.js, src/components/AnswerEditor/index.js, src/components/AnswerTypeSelector/AnswerTypeGrid.js, src/components/AnswerTypeSelector/__snapshots__/AnswerTypeGrid.test.js.snap, src/components/Answers/Dummy/TextArea/__snapshots__/index.test.js.snap, src/components/Answers/Dummy/TextArea/index.js, yarn.lock
This PR enables the TextArea answer type in the Answer type grid.
A test has been added to ensure the answer type renders correctly.
Should be able to add text area answers.
=> Enable adding Text Area answers to the questionnaire.

src/components/Answers/CurrencyAnswer/index.js
Fixes #216 .
Add currency answer.
Add another answer.
Answer type selector should appear above the currency field.
=> Fixes #216 currency icon appearing over icon type selector.

src/components/Answers/CurrencyAnswer/index.js, src/components/App/index.js, src/components/BaseLayout/__snapshots__/BaseLayout.test.js.snap, src/components/BaseLayout/index.js, src/components/Grid/Column.js, src/components/Header/__snapshots__/Header.test.js.snap, src/components/MainCanvas/__snapshots__/index.test.js.snap, src/components/MainCanvas/index.js, src/components/QuestionnaireNav/SectionNav.js, src/components/QuestionnaireNav/index.js, src/components/RichTextEditor/Toolbar.js, src/components/ScrollPane/__snapshots__/index.test.js.snap, src/components/ScrollPane/index.js, src/components/ScrollPane/index.test.js, src/constants/theme.js, src/containers/QuestionnaireCreatePage/QuestionnaireCreatePage.js, src/containers/QuestionnaireDesignPage/QuestionnaireDesignPage.js, src/containers/QuestionnaireDesignPage/__snapshots__/QuestionnaireDesignPage.test.js.snap, src/containers/QuestionnaireMetaPage/QuestionnaireMetaPage.js, src/containers/QuestionnaireMetaPage/__snapshots__/QuestionnaireMetaPage.test.js.snap, src/containers/QuestionnairesPage/QuestionnairesPage.js, src/containers/QuestionnairesPage/__snapshots__/QuestionnairesPage.test.js.snap, yarn.lock
[Trello card](https://trello.com/b/GOqjEepx/eq-author)
Adds `ScrollPanel` component that will add vertical scroll bars if it's children height exceeds the height of it's container.
Additionally, "add section" button is now sticky, should the navigation exceed the height of the browser it will "stick" to the bottom of the viewport.
Also, fixed a lingering issue with the `Column` component having `max-width: NaN` in CSS.
- add enough answers/other content to a page to invoke scrollbars on main content area.
- add enough pages/sections to invoke scrollbars on navigation
=> 142 scrolling behaviour

.travis.yml, config/chimp-common.js, config/chimp.author.js, package.json, src/components/Answers/MultipleChoiceAnswer/Option.js, src/components/Answers/MultipleChoiceAnswer/__snapshots__/MultipleChoiceAnswer.test.js.snap, src/components/Answers/MultipleChoiceAnswer/__snapshots__/Option.test.js.snap, src/components/Answers/MultipleChoiceAnswer/index.js, src/tests/utils/MockResolvers.js, tests/pages/AnswerSelector.page.js, tests/pages/CheckboxAnswer.page.js, tests/pages/DesignQuestionnaire.page.js, tests/spec/issues/checkbox-values-lost-spec.js, tests/spec/smoketest-author-spec.js
This PR implements a functional test for issue #191 which was fixed indirectly whilst refactoring data management #188.
=> Checkbox option test

package.json, src/components/QuestionPageEditor/MetaEditor.js, src/components/QuestionPageEditor/__snapshots__/MetaEditor.test.js.snap, src/components/RichTextEditor/RichTextEditor.test.js, src/components/RichTextEditor/Toolbar.js, src/components/RichTextEditor/Toolbar.test.js, src/components/RichTextEditor/__snapshots__/RichTextEditor.test.js.snap, src/components/RichTextEditor/__snapshots__/Toolbar.test.js.snap, src/components/RichTextEditor/index.js, src/components/SectionEditor/__snapshots__/sectioneditor.test.js.snap, src/components/SectionEditor/index.js, yarn.lock
* Fixes a bunch of bugs with rich text editor (#226, #230, #232).
* Improves whitespace for rich-text content to improve readability. 
* Disables emphasis in guidance section
* Guidance style now mimics runner style
* Multiline text enabled on _section description_ and _question text_
* Adds tests for previously untested parts of RTE
Run tests, review code, test that bugs are fixed
=> Rich text bug fixes

package.json, src/components/Accordion/Accordion.story.js, src/components/Accordion/PanelBody.js, src/components/Accordion/PanelBody.test.js, src/components/Accordion/PanelTitle.js, src/components/Accordion/PanelTitle.test.js, src/components/Accordion/__snapshots__/PanelBody.test.js.snap, src/components/Accordion/__snapshots__/PanelTitle.test.js.snap, src/components/Accordion/__snapshots__/index.test.js.snap, src/components/Accordion/chevron.svg, src/components/Accordion/index.js, src/components/Accordion/index.test.js, src/components/PropertiesPanel/PropertiesPanel.test.js, src/components/PropertiesPanel/__snapshots__/PropertiesPanel.test.js.snap, src/components/PropertiesPanel/index.js, src/containers/QuestionnaireDesignPage/QuestionnaireDesignPage.js, src/containers/QuestionnaireDesignPage/__snapshots__/QuestionnaireDesignPage.test.js.snap, yarn.lock
This PR adds an accordion component to the questionnaire design page.
It displays the page and answer properties for the current page.
Answer properties should persist to the database.
=> Add accordion component

src/components/Toast/ToastList.js, src/components/Toast/ToastList.test.js, src/components/Toast/Transition.js, src/components/Toast/__snapshots__/ToastList.test.js.snap, src/components/Toast/__snapshots__/index.test.js.snap, src/components/Toast/index.js, src/components/Toast/index.test.js, src/components/Toast/story.js, src/utils/fsm.js, src/utils/fsm.test.js, src/utils/timer.js, src/utils/timer.test.js
Adds Toast and ToastList components. 
Review code, run tests, play with stories
=> 214 toast component

package.json, src/components/Menu/Dropdown.js, src/components/Menu/Menu.test.js, src/components/Menu/MenuItem.js, src/components/Menu/MenuList.js, src/components/Menu/MenuScrollPane.js, src/components/Menu/SubMenuItem.js, src/components/Menu/__snapshots__/Menu.test.js.snap, src/components/Menu/icon-arrow.svg, src/components/Menu/index.js, src/components/Menu/story.js, src/components/QuestionnaireMenu/QuestionnaireMenu.test.js, src/components/QuestionnaireMenu/__snapshots__/QuestionnaireMenu.test.js.snap, src/components/QuestionnaireMenu/index.js, src/components/QuestionnaireMenu/schema.json, src/components/QuestionnaireMenu/story.js, src/components/ScrollPane/index.js, yarn.lock
[Trello card](https://trello.com/c/yWibADHi/185-cascading-menu-component-8)
- Added `Menu` component wrapping [react-menu-list](https://github.com/StreakYC/react-menu-list) with styling
- Added a basic `QuestionnaireMenu` implementation
This PR doesn't implement the menu inside the RTE toolbar, however.
- review `Menu` components in the relevant story
- `QuestionnaireMenu` is not considered production-ready, just a reference implementation.
=> 185 Cascading menu component

.storybook/preview-head.html, package.json, src/components/AnswerEditor/__snapshots__/answereditor.test.js.snap, src/components/AnswerEditor/answereditor.test.js, src/components/AnswerEditor/index.js, src/components/AnswerTypeSelector/AnswerTypeButton.js, src/components/AnswerTypeSelector/AnswerTypeGrid.js, src/components/AnswerTypeSelector/__snapshots__/AnswerTypeGrid.test.js.snap, src/components/Answers/DateRange/__snapshots__/index.test.js.snap, src/components/Answers/DateRange/index.js, src/components/Answers/DateRange/index.test.js, src/components/Answers/Dummy/DateRange/__snapshots__/index.test.js.snap, src/components/Answers/Dummy/DateRange/index.js, src/components/Answers/Dummy/DateRange/index.test.js, src/components/Answers/Dummy/DateRange/story.js, src/constants/answer-types.js, yarn.lock
Adds support for DateRange answer type
Run tests, review code, preview through runner and ensure DateRange handled correctly
=> Add support for DateRange types

src/components/Answers/BasicAnswer/__snapshots__/BasicAnswer.test.js.snap, src/components/Answers/BasicAnswer/index.js, src/components/Answers/MultipleChoiceAnswer/MultipleChoiceAnswer.test.js, src/components/Answers/MultipleChoiceAnswer/Option.js, src/components/Answers/MultipleChoiceAnswer/__snapshots__/MultipleChoiceAnswer.test.js.snap, src/components/Answers/MultipleChoiceAnswer/__snapshots__/Option.test.js.snap, src/components/Answers/MultipleChoiceAnswer/index.js, src/components/QuestionPageEditor/QuestionPageEditor.test.js, src/components/QuestionPageEditor/index.js, src/components/withEntityEditor/index.js, src/components/withEntityEditor/index.test.js, src/containers/enhancers/withCreateAnswer.js, src/containers/enhancers/withCreateAnswer.test.js, src/containers/enhancers/withCreateOption.js, src/containers/enhancers/withCreateOption.test.js, src/utils/focusOnEntity.js, src/utils/focusOnEntity.test.js
[Trello](https://trello.com/c/i26T8TQ4/231-spike-revisit-autofocus)
- Adds autofocus to newly created options
WIP
=> Revisit autofocus

src/components/AnswerProperties/AnswerProperties.test.js, src/components/AnswerProperties/__snapshots__/AnswerProperties.test.js.snap, src/components/AnswerProperties/index.js, src/components/PropertiesPanel/__snapshots__/PropertiesPanel.test.js.snap, src/components/PropertiesPanel/index.js, src/containers/AnswerPropertiesContainer/index.js, src/graphql/fragments/answer.graphql
This PR connects the `mandatory` property to the answer properties panel so that when the checkbox is toggled, the value is reflected on the server.
Toggle the answer required checkbox and observe that the value is changed on the API via a GraphQL mutation.
=> Make mandatory checkbox in answer properties work.

src/components/ToggleSwitch/__snapshots__/toggleswitch.test.js.snap, src/components/ToggleSwitch/index.js, src/components/ToggleSwitch/toggleswitch.story.js, src/components/ToggleSwitch/toggleswitch.test.js
This PR introduces a new `ToggleButton` presentational component which is needed for some of the upcoming UI changes to the create a questionnaire page and the properties panel.
See the `ToggleButton` component in the storybook.
=> Add toggle button component, story and test.

src/components/RichTextEditor/PipingMenu.js, src/components/RichTextEditor/RichTextEditor.test.js, src/components/RichTextEditor/entities/PipedValue.js, src/components/RichTextEditor/index.js, src/components/RichTextEditor/utils/replaceEntityText.js
Fixes some issues with piping:
* disables Date Range piping, as this is more complex than first imagined
* handles piped values where the answer has since been deleted
* handles cases where an answer without a label has been piped 
review code, test fixes as outlined above
=> Piping fixes

src/components/QuestionPageEditor/MetaEditor.js, src/components/QuestionPageEditor/__snapshots__/MetaEditor.test.js.snap
Update the placeholder labels as per the Trello card.
Use the netlify link to confirm that placeholder labels have been updated correctly.
All tests and checks should continue to pass.
=> Minor content tweaks.

src/components/ToggleSwitch/__snapshots__/toggleswitch.test.js.snap, src/components/ToggleSwitch/index.js
* Improves colours used for unchecked toggle switch
* Adds `aria` and `role` attributes to improve accessibility
Check code, visually inspect new styles
=> Improve toggle styles

src/containers/QuestionnaireDesignPage/QuestionnaireDesignPage.js, src/containers/QuestionnaireDesignPage/QuestionnaireDesignPage.test.js, src/containers/QuestionnaireDesignPage/__snapshots__/QuestionnaireDesignPage.test.js.snap, src/containers/enhancers/withQuestionnaire.js
Fixes #288 by redirecting to a 404 error if the url tries to point towards a non-existent questionnaire, section or page.  
Program should pass all tests and if a url is entered in the format http://localhost:3000/#/questionnaire/(random_characters)/design/58/94 you should be redirected to a 404 error rather than the program crashing
=> 375 eq author 288 non existent survey link doesnt re direct to a 404 error issue

src/containers/QuestionnaireDesignPage/QuestionnaireDesignPage.js, src/containers/QuestionnaireDesignPage/QuestionnaireDesignPage.test.js, src/containers/QuestionnaireDesignPage/__snapshots__/QuestionnaireDesignPage.test.js.snap, src/containers/enhancers/withQuestionnaire.js
Reverts ONSdigital/eq-author#292
=> Revert "375 eq author 288 non existent survey link doesnt re direct to a 404 error issue"

cypress/integration/author_spec.js, cypress/utils/index.js, src/components/QuestionPageEditor/MetaEditor.js, src/components/QuestionPageEditor/__snapshots__/MetaEditor.test.js.snap, src/components/SectionEditor/__snapshots__/sectioneditor.test.js.snap, src/components/SectionEditor/index.js
… ids from the richTextEditer
Fixes issuse from removing ID  from the richTextEditer fields and resolves an issue with typing in Draftjs on cypress
Should pass all smoketests
=> Fixed issue not being able to update section title.

src/__snapshots__/index.test.js.snap, src/index.test.js
Stub creation of createdAt Date in mock API integration test
tests pass, approach is sound
=> use a fixed date value in mock API integration test

src/components/TextButton/__snapshots__/index.test.js.snap, src/components/TextButton/index.js, src/components/TextButton/index.test.js, src/components/TextButton/story.js
[Trello card](https://trello.com/c/MH36M4rM/376-text-button-component-1)
Adds a simple `TextButton` component.
Review in storybook against trello card
=> eq-376 TextButton component

.storybook/config.js, src/components/AnswerTypeSelector/story.js, src/components/RichTextEditor/RichTextEditor.story.js, src/components/SectionEditor/sectioneditor.story.js
Fixed the broken storyboard components.
All storyboard components should work as expected.
=> Fixing broken storybook components.

src/components/Button/story.js, src/components/ToggleChip/ToggleChip.story.js, src/components/ToggleChip/ToggleChip.test.js, src/components/ToggleChip/__snapshots__/ToggleChip.test.js.snap, src/components/ToggleChip/checked.svg, src/components/ToggleChip/index.js
- Refactoring of initial component created by Sam G.
- Fix linting errors and update snapshots.
- Add test for covering click to focus functionality.
Launch storybook an examine the ToggleChip component. Check that it behaves as expected and matches the design.
All existing tests and checks should pass.
=> Implement toggle chip component.

.storybook/config.js, .storybook/storyshots.storytest.js, .travis.yml, config/jest/svgTransform.js, package.json, src/components/AnswerEditor/answereditor.story.js, src/components/AnswerProperties/story.js, src/components/AnswerTypeSelector/AnswerTypeButton.test.js, src/components/Answers/MultipleChoiceAnswer/MultipleChoiceAnswer.story.js, src/components/Breadcrumb/story.js, src/components/EditorSurface/CanvasSection.story.js, src/components/Grid/story.js, src/components/Header/story.js, src/components/IconDecorated/IconButton/icon-test.svg, src/components/IconDecorated/IconLink/story.js, src/components/IconGrid/story.js, src/components/Menu/story.js, src/components/Nav/story.js, src/components/NavigationSidebar/story.js, src/components/QuestionnaireMeta/story.js, src/components/Toast/story.js, src/tests/setup/throwOnConsole.js, yarn.lock
Implemented storyshot testing.
Tests should pass and by running test:storybook the addition storyshot testing should take place and pass.
=> Implemented storyshot testing

.stylelintrc, src/components/Menu/SubMenuItem.js, src/components/NavigationSidebar/PageNav.js, src/components/ToggleChip/index.js, src/components/ToggleSwitch/__snapshots__/toggleswitch.test.js.snap, src/components/ToggleSwitch/index.js, src/containers/QuestionnairesPage/QuestionnairesTable.js
Disabled some of the more offensive eslint rules. 
yarn lint should report no more errors and eslint disable comments should only be in areas when the rule necessitate.
=> 383 improve stylelint

src/components/Menu/__snapshots__/Menu.test.js.snap, src/components/ScrollPane/__snapshots__/index.test.js.snap, src/components/ScrollPane/index.js
Persists scrollbars so they are always visible, instead of appearing on hover.
Check scrollbars don't disappear when the element is not hovered.
=> Persist scrollbar visibility

src/assets/icon-select.svg, src/components/MovePageModal/ItemSelect.js, src/components/MovePageModal/ItemSelectModal.js, src/components/MovePageModal/ItemSelectModal.test.js, src/components/MovePageModal/__snapshots__/ItemSelect.test.js.snap, src/components/MovePageModal/__snapshots__/ItemSelectModal.test.js.snap, src/components/MovePageModal/icon-move-indicator.svg, src/components/MovePageModal/index.js
Updates the 'move page' functionality with latest stylings.
Check everything still works as expected.
=> Update move page UI to latest design

src/containers/enhancers/withMovePage.js, src/containers/enhancers/withMovePage.test.js
See #358 
Changes look sensible, confirm that bug is no longer reproducible
=> fix inconsistencies with multiple page moves

package.json, yarn.lock
there were utf-8 issues with the old version, the latest version fixes this
=> upgrade to latest version of serve pkg

src/components/BaseLayout/__snapshots__/BaseLayout.test.js.snap, src/components/BaseLayout/index.js, src/components/ExpansionTransition/index.js, src/components/OfflineBanner/OfflineBanner.story.js, src/components/OfflineBanner/OfflineBanner.test.js, src/components/OfflineBanner/__snapshots__/OfflineBanner.test.js.snap, src/components/OfflineBanner/icon-warning.svg, src/components/OfflineBanner/index.js
The app need some way to let the user know when they have dropped their internet connection so they can troubleshoot and that their work may not be being saved. 
Run the app then drop your connection, the alert should be very noticeable and remain on screen until you re-connect. Also tests should pass.
=> Alert user when offline

src/components/Forms/Number/__snapshots__/numberinput.test.js.snap, src/components/Forms/Number/arrow.svg, src/components/Forms/Number/index.js, src/components/Forms/Number/numberinput.test.js, src/components/Forms/story.js, src/components/ToggleSwitch/__snapshots__/toggleswitch.test.js.snap, src/components/ToggleSwitch/index.js, src/components/ToggleSwitch/toggleswitch.story.js
- https://trello.com/c/FcPqON0I/459-update-toggle-switch-and-numeric-field-to-match-new-designs
- Updated toggle component to match new designs
- Removed increment/decrement buttons from number components
- Run tests
- See visual changes in Storybook
=> 459 update toggle and numeric field styles

src/components/RichTextEditor/RichTextEditor.test.js, src/components/RichTextEditor/entities/PipedValue.js, src/components/RichTextEditor/index.js, src/components/RichTextEditor/utils/createFormatStripper.js, src/components/RichTextEditor/utils/mapControlsToFilterConfig.js
Discovered that piping was being removed when formatting is stripped. This PR whitelists piping as allowed formatting.
Tests pass, can pipe values
=> 503 piping broken

src/components/SidebarButton/__snapshots__/index.test.js.snap, src/components/SidebarButton/index.js, src/components/SidebarButton/index.test.js, src/components/SidebarButton/story.js
Adds components for the showing validation overview in the sidebar
Check the story, ensure it matches design
=> Add sidebar buttons for validation overview

package.json, src/apollo/createApolloErrorLink.js, src/components/OfflineBanner/OfflineBanner.story.js, src/components/OfflineBanner/OfflineBanner.test.js, src/components/OfflineBanner/__snapshots__/OfflineBanner.test.js.snap, src/components/OfflineBanner/index.js, src/components/QuestionPageRoute/index.test.js, src/components/SavingIndicator/SavingIndicator.story.js, src/components/SavingIndicator/SavingIndicator.test.js, src/components/SavingIndicator/index.js, src/components/SectionRoute/index.test.js, src/index.js, src/redux/saving/actions.js, src/redux/saving/reducer.js, src/redux/saving/reducer.test.js, yarn.lock
Work to display error banner when API is unreachable, including differentiating between a network error and an API error.
Test should pass
If the API is down, the banner should display when an API call is made.
=> 474 alert users when api is unreachable

package.json, yarn.lock
The firebase ui behind the log in screen was experiencing some issues so this PR aims to fix that.
Check on netlify that you can log out and then log back in again.
=> Fix broken firebase login

src/components/ModalFullScreen/__snapshots__/index.test.js.snap, src/components/ModalFullScreen/index.js, src/components/ModalFullScreen/index.test.js, src/components/ModalFullScreen/story.js, src/constants/theme.js
This is part of a wider piece of work to capture 'Survey Data'.  The UI will require a full-screen modal which this PR implements. 
- Run Tests
- View Storybook
=> Add full screen modal component

src/redux/configureStore.js
This PR aims to fix invalid logic when configuring the store.
The existing logic would never be true and the fake auth implementation would always be used.
All tests and checks pass.
=> Fix invalid auth logic configuring store.

cypress/fixtures/GetQuestionPage.js, cypress/fixtures/GetQuestionnaire.js, cypress/fixtures/createQuestionnaire.js
- Updates cypress fixtures to fix failing cypress tests
- Tests were failing due to inconsistencies between cypress fixtures and actual responses
- Run Tests
- Travis can successfully build and test application
=>  Update cypress fixtures

src/components/MainCanvas/__snapshots__/index.test.js.snap, src/components/MainCanvas/index.js
Fixes the issue of the main canvas area being too narrow.
Check the width is now sufficient and has appropriate padding.
=> Fix width of main canvas area

src/components/DataTable/Controls/AddRowButton.test.js, src/components/DataTable/Controls/DeleteRowButton.test.js, src/components/DataTable/Controls/TableInput.test.js, src/components/DataTable/Controls/TableInputDate.test.js, src/components/DataTable/Controls/TableSelect.test.js, src/components/DataTable/Controls/TableTypeaheadInput.test.js, src/components/DataTable/Controls/__snapshots__/TableSelect.test.js.snap, src/components/DataTable/Elements/Table.test.js, src/components/DataTable/Elements/TableBody.test.js, src/components/DataTable/Elements/TableColumn.test.js, src/components/DataTable/Elements/TableFoot.test.js, src/components/DataTable/Elements/TableHead.test.js, src/components/DataTable/Elements/TableHeadColumn.test.js, src/components/DataTable/Elements/TableRow.test.js
- Improves test coverage for DataTable components. 
- Better to utilize the components exported from `Controls/index.js` and `Elements/index.js`
- Run Tests
- Ensure coverage is above 90%
=> Improve DataTable test coverage

cypress/integration/authenticated/builder_spec.js, package.json, src/components/AnswerEditor/__snapshots__/answereditor.test.js.snap, src/components/AnswerEditor/answereditor.story.js, src/components/AnswerEditor/answereditor.test.js, src/components/AnswerEditor/index.js, src/components/Answers/MultipleChoiceAnswer/MultipleChoiceAnswer.story.js, src/components/Answers/MultipleChoiceAnswer/MultipleChoiceAnswer.test.js, src/components/Answers/MultipleChoiceAnswer/__snapshots__/MultipleChoiceAnswer.test.js.snap, src/components/Answers/MultipleChoiceAnswer/index.js, src/components/QuestionPageEditor/QuestionPageEditor.test.js, src/components/QuestionPageEditor/index.js, src/components/QuestionPageRoute/index.js, src/components/QuestionPageRoute/index.test.js, src/containers/enhancers/withCreateExclusive.js, src/containers/enhancers/withDeleteOption.js, src/graphql/answerFragment.graphql, src/graphql/createAnswer.graphql, src/graphql/createMutuallyExclusiveOption.graphql, src/graphql/fragments/routing-condition.graphql, yarn.lock
This pr adds the front end components to allow it to display the mutually exclusive checkbox.
Checkbox works, publishes to runner correctly, tests pass and are conclusive and ui matches designs.
https://github.com/ONSdigital/eq-author-graphql-schema/pull/56
https://github.com/ONSdigital/eq-publisher/pull/87
https://github.com/ONSdigital/eq-author-api/pull/109
=> 574 mutually exclusive answer options front end

src/components/PillTabs/__snapshots__/index.spec.js.snap, src/components/PillTabs/index.js, src/components/PillTabs/index.spec.js, src/components/PillTabs/story.js
This implements the pill tabs component as per the design. This relies on #420 and so it has the target branch set to it to make reviewing possible.
Load up the storybook and look at the pill tabs component.
=> 468 - Pill tabs - Part 2 Component

src/components/CharacterCounter/__snapshots__/index.test.js.snap, src/components/CharacterCounter/index.js, src/components/CharacterCounter/index.test.js, src/components/CharacterCounter/story.js
- Adds a character counter component as per designs: https://sketch.cloud/s/EldGg/all/author-canvas/author-canvas
- Run tests
- Check new storybook entry
=> Add character counter component

src/components/ContentPicker/ContentPicker.js, src/components/ContentPicker/ContentPicker.test.js, src/components/ContentPicker/ContentPickerPanel.js, src/components/ContentPicker/ContentPickerPanel.test.js, src/components/ContentPicker/ContentPickerSingle.js, src/components/ContentPicker/ContentPickerSingle.test.js, src/components/ContentPicker/ContentPickerTitle.js, src/components/ContentPicker/ContentPickerTitle.test.js, src/components/ContentPicker/PickerOption.js, src/components/ContentPicker/PickerOption.test.js, src/components/ContentPicker/__snapshots__/ContentPicker.test.js.snap, src/components/ContentPicker/__snapshots__/ContentPickerPanel.test.js.snap, src/components/ContentPicker/__snapshots__/ContentPickerSingle.test.js.snap, src/components/ContentPicker/__snapshots__/ContentPickerTitle.test.js.snap, src/components/ContentPicker/__snapshots__/PickerOption.test.js.snap, src/components/ContentPicker/__snapshots__/index.test.js.snap, src/components/ContentPicker/chevron.svg, src/components/ContentPicker/index.js, src/components/ContentPicker/index.test.js, src/components/ContentPickerModal/contentPicker.story.js, src/components/ContentPickerModal/index.js, src/tests/utils/generateMockPiping.js
This PR add the new components behind the new style of content picker.
New content picker looks like the designs and the test should pass, (once they're written).
=> Content picker component

cypress/integration/authenticated/builder_spec.js, package.json, src/components/CharacterCounter/__snapshots__/index.test.js.snap, src/components/CharacterCounter/index.js, src/components/CharacterCounter/index.test.js, src/components/SectionEditor/__snapshots__/SectionEditor.test.js.snap, src/components/SectionEditor/index.js, src/components/SectionRoute/index.test.js, src/graphql/fragments/section.graphql, yarn.lock
- Adds `Alias` input to `Section Editor`
- Run tests
- Test e2e with API and Schema dependencies
=> 571 aliases for sections

src/components/Validation/AnswerValidation.js, src/components/Validation/AnswerValidation.test.js, src/components/Validation/Date/DateValidation.js, src/components/Validation/__snapshots__/AnswerValidation.test.js.snap
Add date validation preview including offset and relative position	
1. Add a date answer.
2. Update the properties.
3. Check that the layout matches the design: https://trello-attachments.s3.amazonaws.com/591461cfdd99b84ee60e44ef/5b45bd5d1c3998ec23a415cd/6c112b5af23b3fb81f89079be123ded5/Validation_panel_buttons.png
=> Bug - Add missing date validation preview

.travis.yml
Fix indentation and add greenkeeper config as requested by greenkeeper 
Ensure CI still runs.
=> Tech Debt - Greenkeeper not running

cypress/integration/authenticated/routing_spec.js, cypress/utils/index.js, scripts/run_e2e_tests_author.sh, src/components/Toast/ToastList.js, src/components/Toast/__snapshots__/ToastList.test.js.snap
This change aims to make cyprus more reliable.
1. Follow the link here: https://travis-ci.org/ONSdigital/eq-author/pull_requests
2. Search for "Bug - Flaky cyprus tests"
3. You should see many green builds in a row.
=> Bug - Flaky cyprus tests

.travis.yml
Re-add removed task causing master deploy to fail
1. Ensure that storybook-build is run during CI job
=> Bug - readd story book build

public/index.html
Full story was partially using build time and runtime environment
variables.
Build time for the script include and runtime to actually hook our
identity to it.
This resulted in an error when the build time was set to false and
runtime was set to true.
To resolve this we now only use runtime environment variables to
determine whether to use full story.
1. Ensure you can enable and disable full story with just docker environment variables.
=> Bug - Full story not fully enabled

src/graphql/fragments/routing-condition.graphql
Noticed a duplicate import line in the routing condition file so I have removed it
Tests pass
=> Removing duplicate import

src/components/PillTabs/__snapshots__/index.spec.js.snap, src/components/PillTabs/index.js
Fix issue where pill tabs growing to take full parent width
- Ensure that the pill tabs don't grow bigger than the children.
=> Bug - Pill tabs growing

cypress/integration/authenticated/validation_spec.js, cypress/utils/index.js, src/components/Validation/Date/DatePreview.js, src/components/Validation/Date/DatePreview.test.js, src/components/Validation/Date/DateValidation.js, src/components/Validation/Date/__snapshots__/DatePreview.test.js.snap, src/components/Validation/Date/__snapshots__/DateValidation.test.js.snap, src/components/Validation/ValidationPills.js, src/components/Validation/ValidationPills.test.js, src/components/Validation/__snapshots__/ValidationPills.test.js.snap, src/constants/validation-entity-types.js
Adds the start date field to the date validation pills and allows the author to publish a schema with a date range validation.
Tests pass, front-end looks good and the e2e implementation works correctly.
=> Implemented validation on start date
